import { ACCESS_CONTROL_POLICY_SPEC, ACCESS_CONTROL_POLICY_TEMPLATE_VERSION } from "./access-control-policy.ts";
import { ACCESS_CONTROL_POLICY_ASSESSMENT_MAPPING, ACCESS_CONTROL_POLICY_ASSESSMENT_MAPPING_VERSION } from "./access-control-policy-assessment-mapping.ts";

export const ACCESS_CONTROL_POLICY_GENERATION_CONTRACT_VERSION = "1.0.0";
type Answer = "implemented" | "partially_implemented" | "not_implemented" | "not_sure" | "not_applicable";
type State = "implemented" | "partial" | "absent" | "uncertain" | "not_applicable";
type Response = { theme: string; controlId: string; questionId: string; answer: Answer; justification?: string | null };
export type AccessControlPolicyGenerationContext = { templateVersion:string; mappingVersion:string; generationContractVersion:string; currentFacts:readonly { capability:string; implementationState:State; policySections:readonly string[] }[]; policyIntent:{ mayDefineNormativeRequirements:true; currentStateIsNotPolicyState:true }; assessmentFacts:readonly { questionId:string; controlId:string; relevance:string; implementationState:State }[]; missingInputs:readonly {key:string;label:string;sectionId:string;required:boolean;expectedType:string;reason:string}[]; conflicts:readonly unknown[]; sectionReadiness:Record<string,"ready"|"partial"|"blocked">; sourceTrace:readonly {sourceType:"assessment"|"workspace"|"document_setup";sourceId:string;controlId?:string;relevance?:string;answer?:Answer}[]; prohibitedInferences:readonly string[]; authentication:{secureAuthenticationState?:State;mfaRequirement:"unknown"}; accessRightsLifecycle:{reviewFrequency:"unknown"}; organization:{name?:string}; scope:{value?:string}; knownInputs:Record<string,unknown> };
export type AccessControlPolicyGenerationInput = { workspace?:{organizationName?:string;scope?:string}; documentSetup?:Record<string,unknown>; assessment?:{responses:readonly Response[];context?:Record<string,"yes"|"no"|"not_sure"|undefined>} };
const value=(a:Answer):State=>a==="partially_implemented"?"partial":a==="not_implemented"?"absent":a==="not_sure"?"uncertain":a;
const present=(v:unknown)=>typeof v==="string"?v.trim().length>0:Array.isArray(v)?v.length>0:v!==undefined&&v!==null;
export function prepareAccessControlPolicyGenerationContext(input:AccessControlPolicyGenerationInput):AccessControlPolicyGenerationContext { const setup=input.documentSetup??{}; const known:Record<string,unknown>={organization_name:input.workspace?.organizationName,scope:input.workspace?.scope,...setup}; const context=input.assessment?.context??{}; const responses=input.assessment?.responses??[]; const facts:Array<{capability:string;implementationState:State;policySections:readonly string[]}>=[]; const trace:Array<{sourceType:"assessment"|"workspace"|"document_setup";sourceId:string;controlId?:string;relevance?:string;answer?:Answer}>=[];
  for(const mapping of ACCESS_CONTROL_POLICY_ASSESSMENT_MAPPING){const response=responses.find(item=>item.theme===mapping.theme&&item.questionId===mapping.questionId); if(!response || (mapping.conditionKey&&context[mapping.conditionKey]!=="yes") || (response.answer==="not_applicable"&&!response.justification?.trim()))continue; const implementationState=value(response.answer); facts.push({capability:mapping.questionId,implementationState,policySections:mapping.policySections}); trace.push({sourceType:"assessment",sourceId:mapping.questionId,controlId:mapping.controlId,relevance:mapping.relevance,answer:response.answer});}
  if(present(known.organization_name))trace.push({sourceType:"workspace",sourceId:"organization_name"}); for(const key of Object.keys(setup))trace.push({sourceType:"document_setup",sourceId:key});
  const missingInputs=ACCESS_CONTROL_POLICY_SPEC.requiredInputs.filter(item=>!present(known[item.id])).map(item=>({key:item.id,label:item.label,sectionId:item.id==="approver"?"policy_review_and_approval":"document_control",required:true,expectedType:item.id==="approver"?"workspace_member":"text",reason:"No explicit permitted source is available."})); const sectionReadiness={} as Record<string,"ready"|"partial"|"blocked">; for(const section of ACCESS_CONTROL_POLICY_SPEC.sections)sectionReadiness[section.id]=section.id==="access_control_principles"?"ready":section.requiredInputs.some(id=>!present(known[id]))?(section.allowOmission?"partial":"blocked"):"ready";
  return {templateVersion:ACCESS_CONTROL_POLICY_TEMPLATE_VERSION,mappingVersion:ACCESS_CONTROL_POLICY_ASSESSMENT_MAPPING_VERSION,generationContractVersion:ACCESS_CONTROL_POLICY_GENERATION_CONTRACT_VERSION,currentFacts:facts,policyIntent:{mayDefineNormativeRequirements:true,currentStateIsNotPolicyState:true},assessmentFacts:facts.map(f=>{const t=trace.find(x=>x.sourceId===f.capability)!;return{questionId:f.capability,controlId:t.controlId!,relevance:t.relevance!,implementationState:f.implementationState};}),missingInputs,conflicts:[],sectionReadiness,sourceTrace:trace,prohibitedInferences:ACCESS_CONTROL_POLICY_SPEC.forbiddenInferences,authentication:{secureAuthenticationState:facts.find(x=>x.capability==="p8_5_001")?.implementationState,mfaRequirement:"unknown"},accessRightsLifecycle:{reviewFrequency:"unknown"},organization:{name:known.organization_name as string|undefined},scope:{value:known.scope as string|undefined},knownInputs:known};
}
