import { organizationalControls } from "../../content/assessment/organizational/organizational-controls.ts";
import { employmentTermsQuestions } from "../../content/assessment/people/employment-terms.ts";
import { postEmploymentResponsibilitiesQuestions } from "../../content/assessment/people/post-employment-responsibilities.ts";
import { confidentialityAgreementsQuestions } from "../../content/assessment/people/confidentiality-agreements.ts";
import { remoteWorkingQuestions } from "../../content/assessment/people/remote-working.ts";
import { technologicalControls } from "../../content/assessment/technological/technological-controls.generated.ts";

export const ACCESS_CONTROL_POLICY_ASSESSMENT_MAPPING_VERSION = "1.0.0";
export type AccessControlPolicyMappingEntry = { theme: "organizational" | "people" | "technological"; controlId: string; questionId: string; questionType: "policy_process" | "application" | "proof_traceability" | "conditional"; relevance: "DIRECTLY_RELEVANT" | "CONTEXTUALLY_RELEVANT"; policySections: readonly string[]; conditionKey?: string; excludeWhenHidden: boolean };
type Q = { id: string; type: AccessControlPolicyMappingEntry["questionType"]; conditionKey?: string | null };
const entry = (theme: AccessControlPolicyMappingEntry["theme"], controlId: string, question: Q, relevance: AccessControlPolicyMappingEntry["relevance"], policySections: readonly string[]): AccessControlPolicyMappingEntry => ({ theme, controlId, questionId: question.id, questionType: question.type, relevance, policySections, ...(question.conditionKey ? { conditionKey: question.conditionKey } : {}), excludeWhenHidden: Boolean(question.conditionKey) });
const org = (id: string, relevance: AccessControlPolicyMappingEntry["relevance"], sections: readonly string[], ids?: readonly string[]) => { const c=organizationalControls.find(x=>x.id===id)!; return c.questions.filter(q=>!ids||ids.includes(q.id)).map(q=>entry("organizational",id,q,relevance,sections)); };
const peopleSources = { "a6-2": employmentTermsQuestions, "a6-5": postEmploymentResponsibilitiesQuestions, "a6-6": confidentialityAgreementsQuestions, "a6-7": remoteWorkingQuestions } as const;
const ppl = (id: keyof typeof peopleSources, relevance: AccessControlPolicyMappingEntry["relevance"], sections: readonly string[], ids?: readonly string[]) => peopleSources[id].filter(q=>!ids||ids.includes(q.id)).map(q=>entry("people",id,q,relevance,sections));
const tech = (id: string, relevance: AccessControlPolicyMappingEntry["relevance"], sections: readonly string[]) => { const c=technologicalControls.find(x=>x.id===id)!; return c.questions.map(q=>entry("technological",id,q,relevance,sections)); };

export const ACCESS_CONTROL_POLICY_ASSESSMENT_MAPPING: readonly AccessControlPolicyMappingEntry[] = [
  ...org("a5-2","CONTEXTUALLY_RELEVANT",["roles_and_responsibilities"]), ...org("a5-3","CONTEXTUALLY_RELEVANT",["access_control_principles","exceptions_compliance"]), ...org("a5-12","CONTEXTUALLY_RELEVANT",["access_restrictions"]),
  ...org("a5-15","DIRECTLY_RELEVANT",["policy_statement","access_control_principles","access_restrictions"]), ...org("a5-16","DIRECTLY_RELEVANT",["identity_and_account_management"]), ...org("a5-17","DIRECTLY_RELEVANT",["authentication"]), ...org("a5-18","DIRECTLY_RELEVANT",["access_request_authorization_provisioning","access_rights_lifecycle","privileged_access"]),
  ...org("a5-19","CONTEXTUALLY_RELEVANT",["remote_external_third_party_access"],["p5_19_004_supplier_access_risk"]), ...org("a5-20","CONTEXTUALLY_RELEVANT",["remote_external_third_party_access"],["p5_20_005_access_clauses"]), ...org("a5-23","CONTEXTUALLY_RELEVANT",["remote_external_third_party_access","logging_monitoring_review"],["p5_23_002","p5_23_003"]),
  ...ppl("a6-2","DIRECTLY_RELEVANT",["roles_and_responsibilities","access_request_authorization_provisioning","access_rights_lifecycle"]), ...ppl("a6-5","DIRECTLY_RELEVANT",["access_rights_lifecycle","remote_external_third_party_access"]), ...ppl("a6-6","CONTEXTUALLY_RELEVANT",["remote_external_third_party_access"],["p6_6_004_external"]), ...ppl("a6-7","CONTEXTUALLY_RELEVANT",["scope","remote_external_third_party_access"]),
  ...tech("a8-2","DIRECTLY_RELEVANT",["privileged_access"]), ...tech("a8-3","DIRECTLY_RELEVANT",["access_restrictions"]), ...tech("a8-4","DIRECTLY_RELEVANT",["access_restrictions"]), ...tech("a8-5","DIRECTLY_RELEVANT",["authentication"]), ...tech("a8-15","DIRECTLY_RELEVANT",["logging_monitoring_review"]), ...tech("a8-16","DIRECTLY_RELEVANT",["logging_monitoring_review"]), ...tech("a8-18","CONTEXTUALLY_RELEVANT",["privileged_access","logging_monitoring_review"]),
];

export function validateAccessControlPolicyAssessmentMapping(): string[] { const m=ACCESS_CONTROL_POLICY_ASSESSMENT_MAPPING, errors:string[]=[]; if(m.length!==83)errors.push(`count:${m.length}`); for(const [t,n] of [["organizational",34],["people",17],["technological",32]] as const)if(m.filter(x=>x.theme===t).length!==n)errors.push(`${t}:count`); if(m.filter(x=>x.relevance==="DIRECTLY_RELEVANT").length!==58)errors.push("direct:count"); if(m.filter(x=>x.relevance==="CONTEXTUALLY_RELEVANT").length!==25)errors.push("context:count"); if(new Set(m.map(x=>`${x.theme}:${x.questionId}`)).size!==m.length)errors.push("duplicate"); return errors; }
