import { AI_DOCUMENT_LABELS } from "./registry.ts";
import type { DocumentSectionSpec, DocumentTemplateSpec, TemplateSource } from "./information-security-policy.ts";

export const INCIDENT_MANAGEMENT_PROCEDURE_DOCUMENT_TYPE = "incident_management_procedure" as const;
export const INCIDENT_MANAGEMENT_PROCEDURE_TEMPLATE_VERSION = "1.0.0";
const section=(id:string,order:number,label:string,generationMode:DocumentSectionSpec["generationMode"],sources:TemplateSource[], requiredInputs: string[] = [], optionalInputs: string[] = [], allowOmission = false, structure?: DocumentSectionSpec["structure"]):DocumentSectionSpec=>({id,order,label,generationMode,sources,requiredInputs,optionalInputs,allowOmission,structure});
export const INCIDENT_MANAGEMENT_WORKFLOW = ["report_detect","log","assess","declare","classify_prioritize","escalate","investigate","contain","eradicate_correct","recover","validate","close","learn_improve"] as const;
export const INCIDENT_MANAGEMENT_TERMS={information_security_event:"An observed occurrence requiring assessment; it is not automatically an incident.",information_security_incident:"An assessed event that requires managed response.",major_incident:"An incident requiring elevated coordination or escalation.",containment:"Measures that limit spread or further impact.",eradication:"Removal or correction of the identified cause or contributing condition.",recovery:"Controlled restoration and validation of normal operation.",evidence:"Information preserved to support assessment, investigation or decisions.",lessons_learned:"Documented learning used to improve future readiness and response."} as const;
export const INCIDENT_MANAGEMENT_PRINCIPLES=["timely reporting","consistent assessment","proportionate response","clear accountability","preservation of evidence","controlled communication","traceability","recovery validation","continual improvement"] as const;
export const INCIDENT_MANAGEMENT_BUSINESS_RULES={documentControlFields:["organization_name","document_id","document_owner","version","classification","status","effective_date","review_date","prepared_by","reviewed_by","approved_by","approval_date","revision_history"],genericRoles:["Management","Procedure Owner","Incident Coordinator/Manager","responders","IT/technical personnel","asset/system owners","users/personnel","Legal/Privacy if applicable","Communications if applicable","HR if applicable","third parties if applicable"],reportFields:["what happened","when observed","reporter","affected asset/system/service","symptoms","actions already taken","evidence reference"],assessmentFlow:"reported event → assessment → incident / not incident",assessmentFactors:["CIA impact","scope","business impact","legal/contractual implications","propagation","urgency"],classificationFactors:["category","severity","impact","urgency","scope","criticality","escalation requirement"],investigationFields:["initial analysis","affected assets","timeline","scope","indicators","hypotheses","related incidents","notes","escalation for expertise"],evidenceHandling:["identification","collection","preservation","integrity","access restriction","chain/traceability","handling records","retention according to applicable requirements"],recordTypes:["incident log","incident report","investigation notes","evidence references","actions","communications","closure info","lessons learned","exercise records"],metricCapabilities:["incident count","detection time","response time","containment time","recovery time","recurrence","reopened incidents"]} as const;
export const INCIDENT_MANAGEMENT_PROCEDURE_SPEC:DocumentTemplateSpec<typeof INCIDENT_MANAGEMENT_PROCEDURE_DOCUMENT_TYPE>={documentType:INCIDENT_MANAGEMENT_PROCEDURE_DOCUMENT_TYPE,label:AI_DOCUMENT_LABELS.incident_management_procedure,version:INCIDENT_MANAGEMENT_PROCEDURE_TEMPLATE_VERSION,sourcePriority:["workspace","assessment","evidence","ai_documents_registry","document_setup","derived","static_template"],requiredInputs:[{id:"organization_name",label:"Organization name",sources:["workspace"],required:true,neverInvent:true},{id:"classification",label:"Document classification",sources:["evidence","ai_documents_registry","document_setup"],required:true,neverInvent:true},{id:"approved_by",label:"Approver",sources:["document_setup"],required:true,neverInvent:true},{id:"review_date",label:"Review date",sources:["evidence","ai_documents_registry","document_setup"],required:true,neverInvent:true}],optionalInputs:["document_owner","procedure_owner","reporting_channels","incident_roles","escalation_roles","severity_model","response_targets","communication_roles","external_notification_requirements","evidence_handling_requirements","exercise_testing_approach"].map(id=>({id,label:id.replaceAll("_"," "),sources:["workspace","assessment","evidence","ai_documents_registry","document_setup"] as TemplateSource[],required:false,neverInvent:true})),  forbiddenInferences: ["SOC", "CSIRT", "IRT", "named responders", "specific reporting channel", "Jira", "ServiceNow", "Slack", "Teams", "SIEM", "EDR", "forensic tool", "regulator", "GDPR 72h", "DPA 24/48h", "response times", "RTO", "specific response times", "specific severity levels", "specific SLA", "specific RTO", "specific RPO", "specific evidence retention duration", "police/lawyer involvement", "specific containment action"],
  validationRules: ["exact document type", "exact 18-section order", "unique section ids", "canonical incident workflow", "missing inputs deterministic"],
  sections: [
    section("document_control", 1, "Document Control", "deterministic", ["workspace", "evidence", "ai_documents_registry", "document_setup"], [], [], false, { requiredBlocks: ["table"], minTableRows: 4 }),
    section("purpose", 2, "Purpose", "ai_later", ["workspace", "document_setup"], [], [], false, { requiredBlocks: ["paragraph"] }),
    section("scope", 3, "Scope", "ai_later", ["workspace", "document_setup"], [], [], false, { requiredBlocks: ["paragraph"] }),
    section("terms_and_definitions", 4, "Terms and Definitions", "static", ["static_template"]),
    section("incident_management_principles", 5, "Incident Management Principles", "static", ["static_template"]),
    section("roles_and_responsibilities", 6, "Roles and Responsibilities", "ai_later", ["workspace", "document_setup"], [], [], false, { requiredBlocks: ["table"], minTableRows: 2 }),
    section("preparation_and_readiness", 7, "Preparation and Readiness", "ai_later", ["assessment", "document_setup"], [], [], false, { requiredBlocks: ["paragraph", "bullet_list"], minBlocks: 2 }),
    section("event_and_incident_reporting", 8, "Event and Incident Reporting", "ai_later", ["assessment", "document_setup"], [], [], false, { requiredBlocks: ["paragraph", "numbered_list"], minBlocks: 2 }),
    section("event_assessment_and_incident_declaration", 9, "Event Assessment and Incident Declaration", "ai_later", ["assessment", "document_setup"], [], [], false, { requiredBlocks: ["paragraph", "numbered_list"], minBlocks: 2 }),
    section("classification_severity_and_prioritization", 10, "Classification, Severity and Prioritization", "ai_later", ["document_setup"], [], [], false, { requiredBlocks: ["paragraph", "table"], minBlocks: 2 }),
    section("escalation_and_communication", 11, "Escalation and Communication", "ai_later", ["document_setup"], [], [], false, { requiredBlocks: ["paragraph", "bullet_list"], minBlocks: 2 }),
    section("investigation_and_diagnosis", 12, "Investigation and Diagnosis", "ai_later", ["assessment", "document_setup"], [], [], false, { requiredBlocks: ["paragraph", "numbered_list"], minBlocks: 2 }),
    section("containment_eradication_and_corrective_action", 13, "Containment, Eradication and Corrective Action", "ai_later", ["assessment", "document_setup"], [], [], false, { requiredBlocks: ["paragraph", "numbered_list"], minBlocks: 2 }),
    section("recovery_and_closure", 14, "Recovery and Closure", "ai_later", ["assessment", "document_setup"], [], [], false, { requiredBlocks: ["paragraph", "numbered_list"], minBlocks: 2 }),
    section("evidence_collection_and_preservation", 15, "Evidence Collection and Preservation", "ai_later", ["evidence", "document_setup"], [], [], false, { requiredBlocks: ["paragraph", "bullet_list"], minBlocks: 2 }),
    section("post_incident_review_and_lessons_learned", 16, "Post-Incident Review and Lessons Learned", "ai_later", ["assessment", "document_setup"], [], [], false, { requiredBlocks: ["paragraph", "bullet_list"], minBlocks: 2 }),
    section("records_monitoring_and_metrics", 17, "Records, Monitoring and Metrics", "ai_later", ["evidence", "document_setup"], [], [], false, { requiredBlocks: ["paragraph", "bullet_list"], minBlocks: 2 }),
    section("procedure_review_and_approval", 18, "Procedure Review and Approval", "deterministic", ["evidence", "ai_documents_registry", "document_setup"], [], [], false, { requiredBlocks: ["table"] }),
  ],
};
export function validateIncidentManagementProcedureSpec(){const s=INCIDENT_MANAGEMENT_PROCEDURE_SPEC,e:string[]=[];if(s.documentType!==INCIDENT_MANAGEMENT_PROCEDURE_DOCUMENT_TYPE||!s.version)e.push("identity");if(s.sections.length!==18||s.sections.some((x,i)=>x.order!==i+1))e.push("order");if(new Set(s.sections.map(x=>x.id)).size!==18)e.push("duplicate");if(INCIDENT_MANAGEMENT_WORKFLOW.length!==13)e.push("workflow");return e;}
