"use client";

import Link from "next/link";
import {
  ChevronLeft, ChevronRight, Download, Eye, File, FileImage, FileSpreadsheet,
  FileText, FilterX, Link2, LoaderCircle, Plus, Replace, Search, Trash2, Unlink, Upload, X,
} from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { useStoredLanguage } from "@/components/language-preference";
import { getCanonicalAssessmentCatalog, type CanonicalAssessmentCatalogControl } from "@/lib/assessment/gap-analysis";
import { createClient } from "@/lib/supabase/client";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { DOCUMENT_TYPE_LABELS, type DocumentType } from "@/lib/evidence/metadata";
import chrome from "@/components/dashboard/dashboard-chrome.module.css";
import { AppSidebar } from "@/components/navigation/app-sidebar";
import { workspaceDisplayName } from "@/lib/workspaces/display-name";
import { readBrowserWorkspaceContext } from "@/lib/workspaces/browser-context";
import styles from "./evidence-room-page.module.css";

type Theme = "organizational" | "people" | "physical" | "technological";
type Evidence = { id: string; workspaceId: string; originalFilename: string; mimeType: string; sizeBytes: number; uploadedBy: string; createdAt: string; updatedAt: string; documentType: DocumentType | null; documentVersion: string | null; effectiveDate: string | null; reviewDate: string | null; documentOwnerId: string | null; documentReviewState: "unknown" | "current" | "review_overdue" };
type EvidenceLink = { id: string; evidenceId: string; workspaceId: string; themeId: Theme; controlId: string; questionId: string; linkedBy: string; linkedAt: string };
type WorkspaceMember = { id: string; label: string };
type EvidenceResponse = { evidence?: Evidence[]; links?: EvidenceLink[]; workspaceMembers?: WorkspaceMember[]; error?: string };
type Metrics = { total: number; linked: number; unlinked: number; questions: number };
type CascadeValue = { theme: Theme | ""; controlId: string; questionId: string };

const ACCEPT = ".pdf,.png,.jpg,.jpeg,.txt,.csv";
const PAGE_SIZE = 10;
const themes: Array<{ value: Theme; label: string }> = [
  { value: "organizational", label: "Organizational" }, { value: "people", label: "People" },
  { value: "physical", label: "Physical" }, { value: "technological", label: "Technological" },
];

function record(value: unknown): Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function value(value: unknown): string { return typeof value === "string" ? value.trim() : ""; }
function formatSize(size: number) { return size < 1024 ? `${size} B` : size < 1024 ** 2 ? `${Math.round(size / 1024)} KB` : `${(size / 1024 ** 2).toFixed(1)} MB`; }
function formatDate(date: string, language: "en" | "fr", time = false) { const parsed = new Date(date); return Number.isNaN(parsed.valueOf()) ? "—" : new Intl.DateTimeFormat(language === "fr" ? "fr-FR" : "en-US", { day: "numeric", month: "short", year: "numeric", ...(time ? { hour: "2-digit", minute: "2-digit" } : {}) }).format(parsed); }
function kind(item: Pick<Evidence, "mimeType" | "originalFilename">) { if (item.mimeType === "application/pdf") return "PDF"; if (item.mimeType === "text/csv") return "CSV"; if (item.mimeType === "text/plain") return "TXT"; if (item.mimeType === "image/png") return "PNG"; if (item.mimeType === "image/jpeg") return "JPEG"; return item.originalFilename.split(".").pop()?.toUpperCase() || "FILE"; }
function iconFor(item: Pick<Evidence, "mimeType" | "originalFilename">, size = 24) { if (item.mimeType === "application/pdf" || item.mimeType === "text/plain") return <FileText size={size} />; if (item.mimeType === "text/csv") return <FileSpreadsheet size={size} />; if (item.mimeType.startsWith("image/")) return <FileImage size={size} />; return <File size={size} />; }
async function body<T extends { error?: string }>(response: Response): Promise<T> { const data = await response.json() as T; if (!response.ok) throw new Error(data.error || "Evidence request failed"); return data; }
function emptyCascade(): CascadeValue { return { theme: "", controlId: "", questionId: "" }; }

function CascadePicker({ value: current, onChange, catalog, idPrefix }: { value: CascadeValue; onChange: (next: CascadeValue) => void; catalog: Record<Theme, CanonicalAssessmentCatalogControl[]>; idPrefix: string }) {
  const controls = current.theme ? catalog[current.theme] : [];
  const control = controls.find((item) => item.id === current.controlId);
  return <div className={styles.cascade}>
    <label><span>1</span>Theme<select id={`${idPrefix}-theme`} value={current.theme} onChange={(event) => onChange({ theme: event.target.value as Theme | "", controlId: "", questionId: "" })}><option value="">Select theme</option>{themes.map((theme) => <option key={theme.value} value={theme.value}>{theme.label}</option>)}</select></label>
    <label><span>2</span>Control<select id={`${idPrefix}-control`} value={current.controlId} disabled={!current.theme} onChange={(event) => onChange({ ...current, controlId: event.target.value, questionId: "" })}><option value="">Select control</option>{controls.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.title}</option>)}</select></label>
    <label><span>3</span>Question<select id={`${idPrefix}-question`} value={current.questionId} disabled={!control} onChange={(event) => onChange({ ...current, questionId: event.target.value })}><option value="">Select question</option>{control?.questions.map((item) => <option key={item.id} value={item.id}>{item.wording}</option>)}</select></label>
  </div>;
}


let globalEvidenceCache: Evidence[] | null = null;
let globalLinksCache: EvidenceLink[] | null = null;
let globalWorkspaceMembersCache: WorkspaceMember[] | null = null;
let globalWorkspaceId: string | null = null;

export function EvidenceRoomPage({ initialWorkspaceId, initialEvidence, initialLinks, initialWorkspaceMembers }: { initialWorkspaceId?: string; initialEvidence?: Evidence[]; initialLinks?: EvidenceLink[]; initialWorkspaceMembers?: WorkspaceMember[] }) {
  const { language } = useStoredLanguage();
  const locale = language === "fr" ? "fr" : "en";
  const [workspaceId, setWorkspaceId] = useState(initialWorkspaceId || ""); const [organization, setOrganization] = useState(""); const [profileName, setProfileName] = useState("");
  const [evidence, setEvidence] = useState<Evidence[]>(globalEvidenceCache || initialEvidence || []); const [links, setLinks] = useState<EvidenceLink[]>(globalLinksCache || initialLinks || []); const [loading, setLoading] = useState(!globalEvidenceCache && initialEvidence === undefined); const [error, setError] = useState("");
  const [workspaceMembers, setWorkspaceMembers] = useState<WorkspaceMember[]>(globalWorkspaceMembersCache || initialWorkspaceMembers || []);
  const [search, setSearch] = useState(""); const [themeFilter, setThemeFilter] = useState<Theme | "">(""); const [controlFilter, setControlFilter] = useState(""); const [typeFilter, setTypeFilter] = useState(""); const [statusFilter, setStatusFilter] = useState<"" | "linked" | "unlinked">(""); const [page, setPage] = useState(1);
  const [details, setDetails] = useState<Evidence | null>(null); const [uploadOpen, setUploadOpen] = useState(false); const [linking, setLinking] = useState(false); const [deleting, setDeleting] = useState(false); const [replacing, setReplacing] = useState(false); const [busy, setBusy] = useState(false);
  const [file, setFile] = useState<File | null>(null); const [cascade, setCascade] = useState<CascadeValue>(emptyCascade); const [linkCascade, setLinkCascade] = useState<CascadeValue>(emptyCascade);
  const fileInput = useRef<HTMLInputElement>(null); const replaceInput = useRef<HTMLInputElement>(null); const catalog = useMemo(() => getCanonicalAssessmentCatalog(locale), [locale]);

  const load = useCallback(async () => {
    if (!workspaceId) { setEvidence([]); setLinks([]); setTimeout(() => setLoading(false), 0); return; }
    setLoading(true); setError("");
    try { const response = await body<EvidenceResponse>(await fetch(`/api/evidence?workspaceId=${encodeURIComponent(workspaceId)}`, { cache: "no-store" })); setEvidence(response.evidence ?? []); globalEvidenceCache = response.evidence ?? []; setLinks(response.links ?? []); globalLinksCache = response.links ?? []; setWorkspaceMembers(response.workspaceMembers ?? []); globalWorkspaceMembersCache = response.workspaceMembers ?? []; }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load evidence."); }
    finally { setLoading(false); }
  }, [workspaceId]);

  useEffect(() => { let alive = true; async function init() { if (!isSupabaseConfigured()) { if (alive) setLoading(false); return; } try { const client = createClient(); const { data: sessionData } = await client.auth.getSession(); let user = sessionData.session?.user ?? null; if (!user) { try { user = (await client.auth.getUser()).data.user ?? null; } catch { user = null; } } const fallback = readBrowserWorkspaceContext(); const metadata = record(user?.user_metadata || fallback.metadata); const onboarding = record(metadata.normcore_onboarding); const owner = record(onboarding.assessment_owner); if (alive) { const nextId = value(onboarding.workspace_creation_id) || fallback.workspaceId; globalWorkspaceId = nextId; setWorkspaceId(nextId); if (!initialWorkspaceId && !globalEvidenceCache) setLoading(true); setOrganization(workspaceDisplayName(metadata)); setProfileName(value(owner.full_name) || value(metadata.full_name) || value(metadata.name) || value(user?.email) || fallback.profileName); } } finally { if (alive) setLoading(false); } } void init(); return () => { alive = false; }; }, []);
  useEffect(() => { if (!workspaceId) return; const isNewWorkspace = globalWorkspaceId !== null && globalWorkspaceId !== workspaceId; if (isNewWorkspace || (!globalEvidenceCache && initialEvidence === undefined)) { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); } else if (initialEvidence !== undefined && !globalEvidenceCache && workspaceId === initialWorkspaceId) { globalWorkspaceId = workspaceId; globalEvidenceCache = initialEvidence || null; globalLinksCache = initialLinks || null; globalWorkspaceMembersCache = initialWorkspaceMembers || null; setLoading(false); } // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [load, workspaceId]);

  const linkedIds = useMemo(() => new Set(links.map((link) => link.evidenceId)), [links]);
  const metrics = useMemo<Metrics>(() => ({ total: evidence.length, linked: evidence.filter((item) => linkedIds.has(item.id)).length, unlinked: evidence.filter((item) => !linkedIds.has(item.id)).length, questions: new Set(links.map((link) => `${link.themeId}:${link.controlId}:${link.questionId}`)).size }), [evidence, linkedIds, links]);
  const controls = themeFilter ? catalog[themeFilter] : [];
  const filtered = useMemo(() => evidence.filter((item) => { const itemLinks = links.filter((link) => link.evidenceId === item.id); return (!search || item.originalFilename.toLowerCase().includes(search.trim().toLowerCase())) && (!typeFilter || kind(item) === typeFilter) && (!statusFilter || (statusFilter === "linked" ? itemLinks.length > 0 : itemLinks.length === 0)) && (!themeFilter || itemLinks.some((link) => link.themeId === themeFilter)) && (!controlFilter || itemLinks.some((link) => link.controlId === controlFilter)); }), [controlFilter, evidence, links, search, statusFilter, themeFilter, typeFilter]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const activePage = Math.min(page, pageCount); const visible = filtered.slice((activePage - 1) * PAGE_SIZE, activePage * PAGE_SIZE);
  const detailLinks = details ? links.filter((link) => link.evidenceId === details.id) : [];
  const documentOwner = details?.documentOwnerId ? workspaceMembers.find((member) => member.id === details.documentOwnerId) : null;
  const hasDocumentMetadata = Boolean(details && (details.documentType || details.documentVersion || details.effectiveDate || details.reviewDate || details.documentOwnerId));
  const profile = profileName || "—";

  function resetUpload() { setFile(null); setCascade(emptyCascade()); setError(""); if (fileInput.current) fileInput.current.value = ""; }
  function clearFilters() { setSearch(""); setThemeFilter(""); setControlFilter(""); setTypeFilter(""); setStatusFilter(""); }
  async function upload() { if (!file || !workspaceId || busy) return; setBusy(true); setError(""); try { const form = new FormData(); form.set("workspaceId", workspaceId); form.set("file", file); if (cascade.questionId) { form.set("themeId", cascade.theme); form.set("controlId", cascade.controlId); form.set("questionId", cascade.questionId); } await body(await fetch("/api/evidence", { method: "POST", body: form })); setUploadOpen(false); resetUpload(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to upload evidence."); } finally { setBusy(false); } }
  async function addLink() { if (!details || !linkCascade.questionId || !workspaceId || busy) return; setBusy(true); setError(""); try { await body(await fetch(`/api/evidence/${encodeURIComponent(details.id)}/links`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ workspaceId, themeId: linkCascade.theme, controlId: linkCascade.controlId, questionId: linkCascade.questionId }) })); setLinking(false); setLinkCascade(emptyCascade()); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to link evidence."); } finally { setBusy(false); } }
  async function unlink(link: EvidenceLink) { if (!details || !workspaceId || busy) return; setBusy(true); setError(""); try { await body(await fetch(`/api/evidence/${encodeURIComponent(details.id)}/links/${encodeURIComponent(link.id)}?workspaceId=${encodeURIComponent(workspaceId)}`, { method: "DELETE" })); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to unlink evidence."); } finally { setBusy(false); } }
  async function download(item: Evidence) { if (!workspaceId || busy) return; setBusy(true); setError(""); try { const data = await body<{ signedUrl?: string; error?: string }>(await fetch(`/api/evidence/${encodeURIComponent(item.id)}/download?workspaceId=${encodeURIComponent(workspaceId)}`)); if (!data.signedUrl) throw new Error("Signed download URL unavailable."); window.open(data.signedUrl, "_blank", "noopener,noreferrer"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to open evidence."); } finally { setBusy(false); } }
  async function replace() { if (!details || !file || !workspaceId || busy) return; setBusy(true); setError(""); try { const form = new FormData(); form.set("workspaceId", workspaceId); form.set("file", file); const result = await body<{ evidence?: Evidence; error?: string }>(await fetch(`/api/evidence/${encodeURIComponent(details.id)}/replace`, { method: "POST", body: form })); setDetails(result.evidence ?? details); setReplacing(false); setFile(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to replace evidence."); } finally { setBusy(false); } }
  async function remove() { if (!details || !workspaceId || busy) return; setBusy(true); setError(""); try { await body(await fetch(`/api/evidence/${encodeURIComponent(details.id)}?workspaceId=${encodeURIComponent(workspaceId)}`, { method: "DELETE" })); setDetails(null); setDeleting(false); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to delete evidence."); } finally { setBusy(false); } }
  function questionMeta(link: EvidenceLink) { const control = catalog[link.themeId].find((item) => item.id === link.controlId); const question = control?.questions.find((item) => item.id === link.questionId); return { control, question }; }

  return <main className={chrome.shell}>
    <AppSidebar organization={organization} workspaceId={workspaceId} />
    <section className={`${chrome.content} ${styles.content}`}><header className={chrome.topbar}><div className={chrome.crumb}><span>{organization}</span><b>/</b><strong>Evidence Room</strong></div><div className={chrome.profileTools}><span className={chrome.language}>EN / FR</span><span className={chrome.workspaceStatus}><i />{workspaceId ? "Workspace active" : "Setup"}</span><span className={chrome.profileName}>{profile}</span><span className={chrome.avatar}>{profile.charAt(0).toUpperCase()}</span></div></header>
      <section className={styles.overview}><div className={styles.heading}><h1>Evidence Room</h1><button type="button" className={styles.primary} disabled={!workspaceId} onClick={() => { resetUpload(); setUploadOpen(true); }}><Upload size={19} />Upload evidence</button></div><div className={styles.kpis}><Kpi icon={<FileText />} label="Total evidence" value={metrics.total} /><Kpi icon={<Link2 />} label="Linked evidence" value={metrics.linked} tone="blue" /><Kpi icon={<Unlink />} label="Unlinked evidence" value={metrics.unlinked} tone="red" /><Kpi icon={<File />} label="Questions with evidence" value={metrics.questions} tone="purple" /></div><div className={styles.filters}><label className={styles.search}><Search size={19} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search evidence" /></label><select value={themeFilter} onChange={(event) => { setThemeFilter(event.target.value as Theme | ""); setControlFilter(""); }}><option value="">All themes</option>{themes.map((theme) => <option key={theme.value} value={theme.value}>{theme.label}</option>)}</select><select value={controlFilter} disabled={!themeFilter} onChange={(event) => setControlFilter(event.target.value)}><option value="">All controls</option>{controls.map((control) => <option key={control.id} value={control.id}>{control.code} — {control.title}</option>)}</select><select value={typeFilter} onChange={(event) => setTypeFilter(event.target.value)}><option value="">All file types</option>{["PDF", "PNG", "JPEG", "TXT", "CSV"].map((type) => <option key={type}>{type}</option>)}</select><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as "" | "linked" | "unlinked")}><option value="">All link statuses</option><option value="linked">Linked</option><option value="unlinked">Unlinked</option></select><button type="button" className={styles.clear} onClick={clearFilters}><FilterX size={18} />Clear filters</button></div></section>
      <section className={styles.library}><header><h2>Evidence library <em>{filtered.length}</em></h2></header>{error && <p className={styles.error} role="alert">{error}</p>}<div className={styles.tableWrap}><table><thead><tr><th>Evidence</th><th>Type</th><th>Size</th><th>Uploaded by</th><th>Uploaded</th><th>Linked to</th><th>Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={7} className={styles.empty}><LoaderCircle className={styles.spin} />Loading evidence…</td></tr> : visible.length ? visible.map((item) => { const count = links.filter((link) => link.evidenceId === item.id).length; return <tr key={item.id} tabIndex={0} onClick={() => setDetails(item)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setDetails(item); } }}><td><span className={`${styles.fileIcon} ${styles[kind(item).toLowerCase()]}`}>{iconFor(item)}</span><strong>{item.originalFilename}</strong></td><td>{kind(item)}</td><td>{formatSize(item.sizeBytes)}</td><td>{item.uploadedBy === profile ? profile : item.uploadedBy ? `${item.uploadedBy.slice(0, 8)}…` : "—"}</td><td>{formatDate(item.createdAt, locale)}</td><td>{count ? <span className={styles.linked}><Link2 size={17} />{count} question{count > 1 ? "s" : ""}</span> : <span className={styles.unlinked}>Unlinked</span>}</td><td><button type="button" className={styles.viewDetails} onClick={(event) => { event.stopPropagation(); setDetails(item); }}><ChevronRight size={17} />View details</button></td></tr>; }) : <tr><td colSpan={7} className={styles.empty}>No evidence yet. Upload the first file to build your evidence library.</td></tr>}</tbody></table></div>{filtered.length > PAGE_SIZE && <Pagination page={page} pageCount={pageCount} onChange={setPage} />}</section>
    </section>
    {uploadOpen && <Modal title="Upload evidence" close={() => !busy && setUploadOpen(false)}><button type="button" className={styles.dropzone} onClick={() => fileInput.current?.click()}><Upload size={25} /><strong>Choose a file</strong><span>PDF, PNG, JPEG, TXT, CSV · Max 10 MB</span></button><input ref={fileInput} className={styles.hidden} type="file" accept={ACCEPT} onChange={(event) => setFile(event.target.files?.[0] ?? null)} />{file && <SelectedFile file={file} clear={() => { setFile(null); if (fileInput.current) fileInput.current.value = ""; }} />}<hr /><div className={styles.modalSectionTitle}>Link to Assessment <small>Optional</small><p>Choose a question now, or link it later.</p></div><CascadePicker value={cascade} onChange={setCascade} catalog={catalog} idPrefix="upload" /><footer className={styles.modalFooter}><button type="button" className={styles.textButton} disabled={busy} onClick={() => void upload()}>Upload without linking</button><button type="button" className={styles.secondary} disabled={busy} onClick={() => setUploadOpen(false)}>Cancel</button><button type="button" className={styles.primary} disabled={!file || !cascade.questionId || busy} onClick={() => void upload()}>{busy ? "Uploading…" : <><Link2 size={17} />Upload & link</>}</button></footer></Modal>}
    {details && <Modal title="Evidence details" close={() => !busy && setDetails(null)}>
      <div className={styles.detailFile}><span className={`${styles.fileIcon} ${styles[kind(details).toLowerCase()]}`}>{iconFor(details, 34)}</span><h2>{details.originalFilename}</h2><span className={detailLinks.length ? styles.statusLinked : styles.unlinked}>{detailLinks.length ? "Linked" : "Unlinked"}</span></div>
      <div className={styles.metadata}><span>File type<b>{kind(details)}</b></span><span>Uploaded by<b>{details.uploadedBy ? `${details.uploadedBy.slice(0, 8)}…` : "—"}</b></span><span>Size<b>{formatSize(details.sizeBytes)}</b></span><span>Uploaded at<b>{formatDate(details.createdAt, locale, true)}</b></span></div>
      {hasDocumentMetadata && <div className={`${styles.metadata} ${styles.documentMetadata}`}>
        {details.documentType && <span>Document type<b>{DOCUMENT_TYPE_LABELS[details.documentType]}</b></span>}
        {details.documentVersion && <span>Version<b>{details.documentVersion}</b></span>}
        {details.effectiveDate && <span>Effective date<b>{formatDate(details.effectiveDate, locale)}</b></span>}
        {details.reviewDate && <span>Review date<b>{formatDate(details.reviewDate, locale)}</b></span>}
        {details.documentOwnerId && <span>Document owner<b>{documentOwner?.label ?? "Workspace member"}</b></span>}
      </div>}
      <hr /><div className={styles.linkedTitle}>Linked questions <em>{detailLinks.length}</em></div><div className={styles.questionLinks}>{detailLinks.map((link) => { const meta = questionMeta(link); return <article key={link.id}><FileText size={27} /><div><strong>{meta.control?.code ?? link.controlId} — {meta.control?.title ?? link.controlId}</strong><small>{themes.find((theme) => theme.value === link.themeId)?.label}</small><p>{meta.question?.wording ?? link.questionId}</p></div><Link prefetch={true} href={`/assessment/${link.themeId}/${link.controlId}#${link.questionId}`}><Eye size={16} />View control</Link><button type="button" disabled={busy} onClick={() => void unlink(link)}><Unlink size={16} />Unlink</button></article>; })}</div>{linking ? <div className={styles.inlineLink}><CascadePicker value={linkCascade} onChange={setLinkCascade} catalog={catalog} idPrefix="link" /><div><button type="button" className={styles.secondary} onClick={() => setLinking(false)}>Cancel</button><button type="button" className={styles.primary} disabled={!linkCascade.questionId || busy} onClick={() => void addLink()}><Link2 size={16} />Link question</button></div></div> : <button type="button" className={styles.addLink} onClick={() => { setLinkCascade(emptyCascade()); setLinking(true); }}><Plus size={20} />Link to another question <small>Adds a link without duplicating the file.</small></button>}<footer className={styles.detailFooter}><button type="button" onClick={() => void download(details)}><Eye size={17} />View</button><button type="button" onClick={() => void download(details)}><Download size={17} />Download</button><button type="button" onClick={() => { setFile(null); setReplacing(true); }}><Replace size={17} />Replace file</button><button type="button" className={styles.danger} onClick={() => setDeleting(true)}><Trash2 size={17} />Delete evidence</button></footer>
    </Modal>}
    {replacing && details && <Modal title="Replace file" close={() => !busy && setReplacing(false)}><p className={styles.confirmText}>The evidence identity and all existing question links will be preserved.</p><button type="button" className={styles.dropzone} onClick={() => replaceInput.current?.click()}><Replace size={24} /><strong>Choose replacement file</strong><span>PDF, PNG, JPEG, TXT, CSV · Max 10 MB</span></button><input ref={replaceInput} className={styles.hidden} type="file" accept={ACCEPT} onChange={(event) => setFile(event.target.files?.[0] ?? null)} />{file && <SelectedFile file={file} clear={() => setFile(null)} />}<footer className={styles.modalFooter}><button type="button" className={styles.secondary} onClick={() => setReplacing(false)}>Cancel</button><button type="button" className={styles.primary} disabled={!file || busy} onClick={() => void replace()}>{busy ? "Replacing…" : "Replace file"}</button></footer></Modal>}
    {deleting && details && <Modal title="Delete evidence" close={() => !busy && setDeleting(false)}><p className={styles.confirmText}>This deletes the file and all of its linked questions. This action cannot be undone.</p><footer className={styles.modalFooter}><button type="button" className={styles.secondary} onClick={() => setDeleting(false)}>Cancel</button><button type="button" className={styles.deleteButton} disabled={busy} onClick={() => void remove()}>{busy ? "Deleting…" : "Delete evidence"}</button></footer></Modal>}
  </main>;
}

function Kpi({ icon, label, value, tone = "aqua" }: { icon: React.ReactNode; label: string; value: number; tone?: string }) { return <article className={`${styles.kpi} ${styles[tone]}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></article>; }
function SelectedFile({ file, clear }: { file: File; clear: () => void }) { const item = { mimeType: file.type, originalFilename: file.name }; return <div className={styles.selectedFile}><span className={`${styles.fileIcon} ${styles[kind(item).toLowerCase()]}`}>{iconFor(item)}</span><div><strong>{file.name}</strong><small>{kind(item)} · {formatSize(file.size)}</small></div><button type="button" onClick={clear} aria-label="Remove selected file"><X size={19} /></button></div>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className={styles.overlay} role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) close(); }}><section className={styles.modal} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button type="button" aria-label="Close" onClick={close}><X size={22} /></button></header>{children}</section></div>; }
function Pagination({ page, pageCount, onChange }: { page: number; pageCount: number; onChange: (page: number) => void }) { return <nav className={styles.pagination} aria-label="Evidence pages"><button type="button" disabled={page === 1} onClick={() => onChange(page - 1)}><ChevronLeft /></button>{Array.from({ length: pageCount }, (_, index) => <button type="button" className={page === index + 1 ? styles.currentPage : ""} key={index} onClick={() => onChange(index + 1)}>{index + 1}</button>)}<button type="button" disabled={page === pageCount} onClick={() => onChange(page + 1)}><ChevronRight /></button></nav>; }
