"use client";

import Link from "next/link";
import {
  ChevronLeft, ChevronRight, Download, Eye, File, FileImage, FileSpreadsheet,
  FileText, FilterX, Link2, LoaderCircle, Plus, Replace, Search, Trash2, Unlink, Upload, X,
} from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { useStoredLanguage } from "@/components/language-preference";
import { LanguageToggle } from "@/components/language-toggle";
import { getCanonicalAssessmentCatalog, type CanonicalAssessmentCatalogControl } from "@/lib/assessment/gap-analysis";
import { createClient } from "@/lib/supabase/client";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { DOCUMENT_TYPE_LABELS, type DocumentType } from "@/lib/evidence/metadata";
import chrome from "@/components/dashboard/dashboard-chrome.module.css";
import { AppSidebar } from "@/components/navigation/app-sidebar";
import { workspaceDisplayName } from "@/lib/workspaces/display-name";
import { readBrowserWorkspaceContext } from "@/lib/workspaces/browser-context";
import styles from "./evidence-room-page.module.css";

type Theme = "organizational" | "people" | "physical" | "technological";
type Evidence = { id: string; workspaceId: string; originalFilename: string; mimeType: string; sizeBytes: number; uploadedBy: string; createdAt: string; updatedAt: string; documentType: DocumentType | null; documentVersion: string | null; effectiveDate: string | null; reviewDate: string | null; documentOwnerId: string | null; documentReviewState: "unknown" | "current" | "review_overdue" };
type EvidenceLink = { id: string; evidenceId: string; workspaceId: string; themeId: Theme; controlId: string; questionId: string; linkedBy: string; linkedAt: string };
type WorkspaceMember = { id: string; label: string };
type EvidenceResponse = { evidence?: Evidence[]; links?: EvidenceLink[]; workspaceMembers?: WorkspaceMember[]; error?: string };
type Metrics = { total: number; linked: number; unlinked: number; questions: number };
type CascadeValue = { theme: Theme | ""; controlId: string; questionId: string };

const ACCEPT = ".pdf,.png,.jpg,.jpeg,.txt,.csv";
const PAGE_SIZE = 10;
const themes: Array<{ value: Theme; en: string; fr: string }> = [
  { value: "organizational", en: "Organizational", fr: "Organisationnel" }, { value: "people", en: "People", fr: "Personnes" },
  { value: "physical", en: "Physical", fr: "Physique" }, { value: "technological", en: "Technological", fr: "Technologique" },
];

function record(value: unknown): Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function value(value: unknown): string { return typeof value === "string" ? value.trim() : ""; }
function formatSize(size: number) { return size < 1024 ? `${size} B` : size < 1024 ** 2 ? `${Math.round(size / 1024)} KB` : `${(size / 1024 ** 2).toFixed(1)} MB`; }
function formatDate(date: string, language: "en" | "fr", time = false) { const parsed = new Date(date); return Number.isNaN(parsed.valueOf()) ? "—" : new Intl.DateTimeFormat(language === "fr" ? "fr-FR" : "en-US", { day: "numeric", month: "short", year: "numeric", ...(time ? { hour: "2-digit", minute: "2-digit" } : {}) }).format(parsed); }
function kind(item: Pick<Evidence, "mimeType" | "originalFilename">) { if (item.mimeType === "application/pdf") return "PDF"; if (item.mimeType === "text/csv") return "CSV"; if (item.mimeType === "text/plain") return "TXT"; if (item.mimeType === "image/png") return "PNG"; if (item.mimeType === "image/jpeg") return "JPEG"; return item.originalFilename.split(".").pop()?.toUpperCase() || "FILE"; }
function iconFor(item: Pick<Evidence, "mimeType" | "originalFilename">, size = 24) { if (item.mimeType === "application/pdf" || item.mimeType === "text/plain") return <FileText size={size} />; if (item.mimeType === "text/csv") return <FileSpreadsheet size={size} />; if (item.mimeType.startsWith("image/")) return <FileImage size={size} />; return <File size={size} />; }
async function body<T extends { error?: string }>(response: Response): Promise<T> { const data = await response.json() as T; if (!response.ok) throw new Error(data.error || "Evidence request failed"); return data; }
function evidenceError(message: string, locale: "en" | "fr") {
  if (locale !== "fr") return message;
  const map: Record<string, string> = {
    "Evidence request failed": "La requête liée aux preuves a échoué.",
    "Unable to load evidence.": "Impossible de charger les preuves.",
    "Unable to upload evidence.": "Impossible d'importer la preuve.",
    "Unable to link evidence.": "Impossible de lier la preuve.",
    "Unable to unlink evidence.": "Impossible de délier la preuve.",
    "Signed download URL unavailable.": "Lien de téléchargement indisponible.",
    "Unable to open evidence.": "Impossible d'ouvrir la preuve.",
    "Unable to replace evidence.": "Impossible de remplacer la preuve.",
    "Unable to delete evidence.": "Impossible de supprimer la preuve.",
  };
  return map[message] ?? message;
}
function emptyCascade(): CascadeValue { return { theme: "", controlId: "", questionId: "" }; }

function CascadePicker({ value: current, onChange, catalog, idPrefix, locale }: { value: CascadeValue; onChange: (next: CascadeValue) => void; catalog: Record<Theme, CanonicalAssessmentCatalogControl[]>; idPrefix: string; locale: "en" | "fr" }) {
  const controls = current.theme ? catalog[current.theme] : [];
  const control = controls.find((item) => item.id === current.controlId);
  return <div className={styles.cascade}>
    <label><span>1</span>{locale === "fr" ? "Thème" : "Theme"}<select id={`${idPrefix}-theme`} value={current.theme} onChange={(event) => onChange({ theme: event.target.value as Theme | "", controlId: "", questionId: "" })}><option value="">{locale === "fr" ? "Sélectionner un thème" : "Select theme"}</option>{themes.map((theme) => <option key={theme.value} value={theme.value}>{theme[locale]}</option>)}</select></label>
    <label><span>2</span>{locale === "fr" ? "Contrôle" : "Control"}<select id={`${idPrefix}-control`} value={current.controlId} disabled={!current.theme} onChange={(event) => onChange({ ...current, controlId: event.target.value, questionId: "" })}><option value="">{locale === "fr" ? "Sélectionner un contrôle" : "Select control"}</option>{controls.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.title}</option>)}</select></label>
    <label><span>3</span>{locale === "fr" ? "Question" : "Question"}<select id={`${idPrefix}-question`} value={current.questionId} disabled={!control} onChange={(event) => onChange({ ...current, questionId: event.target.value })}><option value="">{locale === "fr" ? "Sélectionner une question" : "Select question"}</option>{control?.questions.map((item) => <option key={item.id} value={item.id}>{item.wording}</option>)}</select></label>
  </div>;
}


let globalEvidenceCache: Evidence[] | null = null;
let globalLinksCache: EvidenceLink[] | null = null;
let globalWorkspaceMembersCache: WorkspaceMember[] | null = null;
let globalWorkspaceId: string | null = null;

export function EvidenceRoomPage({ initialWorkspaceId, initialEvidence, initialLinks, initialWorkspaceMembers }: { initialWorkspaceId?: string; initialEvidence?: Evidence[]; initialLinks?: EvidenceLink[]; initialWorkspaceMembers?: WorkspaceMember[] }) {
  const { language } = useStoredLanguage();
  const locale = language === "fr" ? "fr" : "en";
  const [workspaceId, setWorkspaceId] = useState(initialWorkspaceId || ""); const [organization, setOrganization] = useState(""); const [profileName, setProfileName] = useState("");
  const [evidence, setEvidence] = useState<Evidence[]>(globalEvidenceCache || initialEvidence || []); const [links, setLinks] = useState<EvidenceLink[]>(globalLinksCache || initialLinks || []); const [loading, setLoading] = useState(!globalEvidenceCache && initialEvidence === undefined); const [error, setError] = useState("");
  const [workspaceMembers, setWorkspaceMembers] = useState<WorkspaceMember[]>(globalWorkspaceMembersCache || initialWorkspaceMembers || []);
  const [search, setSearch] = useState(""); const [themeFilter, setThemeFilter] = useState<Theme | "">(""); const [controlFilter, setControlFilter] = useState(""); const [typeFilter, setTypeFilter] = useState(""); const [statusFilter, setStatusFilter] = useState<"" | "linked" | "unlinked">(""); const [page, setPage] = useState(1);
  const [details, setDetails] = useState<Evidence | null>(null); const [uploadOpen, setUploadOpen] = useState(false); const [linking, setLinking] = useState(false); const [deleting, setDeleting] = useState(false); const [replacing, setReplacing] = useState(false); const [busy, setBusy] = useState(false);
  const [file, setFile] = useState<File | null>(null); const [cascade, setCascade] = useState<CascadeValue>(emptyCascade); const [linkCascade, setLinkCascade] = useState<CascadeValue>(emptyCascade);
  const fileInput = useRef<HTMLInputElement>(null); const replaceInput = useRef<HTMLInputElement>(null); const catalog = useMemo(() => getCanonicalAssessmentCatalog(locale), [locale]);

  const load = useCallback(async () => {
    if (!workspaceId) { setEvidence([]); setLinks([]); setTimeout(() => setLoading(false), 0); return; }
    setLoading(true); setError("");
    try { const response = await body<EvidenceResponse>(await fetch(`/api/evidence?workspaceId=${encodeURIComponent(workspaceId)}`, { cache: "no-store" })); setEvidence(response.evidence ?? []); globalEvidenceCache = response.evidence ?? []; setLinks(response.links ?? []); globalLinksCache = response.links ?? []; setWorkspaceMembers(response.workspaceMembers ?? []); globalWorkspaceMembersCache = response.workspaceMembers ?? []; }
    catch (cause) { setError(evidenceError(cause instanceof Error ? cause.message : "Unable to load evidence.", locale)); }
    finally { setLoading(false); }
  }, [workspaceId]);

  useEffect(() => { let alive = true; async function init() { if (!isSupabaseConfigured()) { if (alive) setLoading(false); return; } try { const client = createClient(); const { data: sessionData } = await client.auth.getSession(); let user = sessionData.session?.user ?? null; if (!user) { try { user = (await client.auth.getUser()).data.user ?? null; } catch { user = null; } } const fallback = readBrowserWorkspaceContext(); const metadata = record(user?.user_metadata || fallback.metadata); const onboarding = record(metadata.normcore_onboarding); const owner = record(onboarding.assessment_owner); if (alive) { const nextId = value(onboarding.workspace_creation_id) || fallback.workspaceId; globalWorkspaceId = nextId; setWorkspaceId(nextId); if (!initialWorkspaceId && !globalEvidenceCache) setLoading(true); setOrganization(workspaceDisplayName(metadata)); setProfileName(value(owner.full_name) || value(metadata.full_name) || value(metadata.name) || value(user?.email) || fallback.profileName); } } finally { if (alive) setLoading(false); } } void init(); return () => { alive = false; }; }, []);
  useEffect(() => { if (!workspaceId) return; const isNewWorkspace = globalWorkspaceId !== null && globalWorkspaceId !== workspaceId; if (isNewWorkspace || (!globalEvidenceCache && initialEvidence === undefined)) { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); } else if (initialEvidence !== undefined && !globalEvidenceCache && workspaceId === initialWorkspaceId) { globalWorkspaceId = workspaceId; globalEvidenceCache = initialEvidence || null; globalLinksCache = initialLinks || null; globalWorkspaceMembersCache = initialWorkspaceMembers || null; setLoading(false); } // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [load, workspaceId]);

  const linkedIds = useMemo(() => new Set(links.map((link) => link.evidenceId)), [links]);
  const metrics = useMemo<Metrics>(() => ({ total: evidence.length, linked: evidence.filter((item) => linkedIds.has(item.id)).length, unlinked: evidence.filter((item) => !linkedIds.has(item.id)).length, questions: new Set(links.map((link) => `${link.themeId}:${link.controlId}:${link.questionId}`)).size }), [evidence, linkedIds, links]);
  const controls = themeFilter ? catalog[themeFilter] : [];
  const filtered = useMemo(() => evidence.filter((item) => { const itemLinks = links.filter((link) => link.evidenceId === item.id); return (!search || item.originalFilename.toLowerCase().includes(search.trim().toLowerCase())) && (!typeFilter || kind(item) === typeFilter) && (!statusFilter || (statusFilter === "linked" ? itemLinks.length > 0 : itemLinks.length === 0)) && (!themeFilter || itemLinks.some((link) => link.themeId === themeFilter)) && (!controlFilter || itemLinks.some((link) => link.controlId === controlFilter)); }), [controlFilter, evidence, links, search, statusFilter, themeFilter, typeFilter]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const activePage = Math.min(page, pageCount); const visible = filtered.slice((activePage - 1) * PAGE_SIZE, activePage * PAGE_SIZE);
  const detailLinks = details ? links.filter((link) => link.evidenceId === details.id) : [];
  const documentOwner = details?.documentOwnerId ? workspaceMembers.find((member) => member.id === details.documentOwnerId) : null;
  const hasDocumentMetadata = Boolean(details && (details.documentType || details.documentVersion || details.effectiveDate || details.reviewDate || details.documentOwnerId));
  const profile = profileName || "—";

  function resetUpload() { setFile(null); setCascade(emptyCascade()); setError(""); if (fileInput.current) fileInput.current.value = ""; }
  function clearFilters() { setSearch(""); setThemeFilter(""); setControlFilter(""); setTypeFilter(""); setStatusFilter(""); }
  async function upload() { if (!file || !workspaceId || busy) return; setBusy(true); setError(""); try { const form = new FormData(); form.set("workspaceId", workspaceId); form.set("file", file); if (cascade.questionId) { form.set("themeId", cascade.theme); form.set("controlId", cascade.controlId); form.set("questionId", cascade.questionId); } await body(await fetch("/api/evidence", { method: "POST", body: form })); setUploadOpen(false); resetUpload(); await load(); } catch (cause) { setError(evidenceError(cause instanceof Error ? cause.message : "Unable to upload evidence.", locale)); } finally { setBusy(false); } }
  async function addLink() { if (!details || !linkCascade.questionId || !workspaceId || busy) return; setBusy(true); setError(""); try { await body(await fetch(`/api/evidence/${encodeURIComponent(details.id)}/links`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ workspaceId, themeId: linkCascade.theme, controlId: linkCascade.controlId, questionId: linkCascade.questionId }) })); setLinking(false); setLinkCascade(emptyCascade()); await load(); } catch (cause) { setError(evidenceError(cause instanceof Error ? cause.message : "Unable to link evidence.", locale)); } finally { setBusy(false); } }
  async function unlink(link: EvidenceLink) { if (!details || !workspaceId || busy) return; setBusy(true); setError(""); try { await body(await fetch(`/api/evidence/${encodeURIComponent(details.id)}/links/${encodeURIComponent(link.id)}?workspaceId=${encodeURIComponent(workspaceId)}`, { method: "DELETE" })); await load(); } catch (cause) { setError(evidenceError(cause instanceof Error ? cause.message : "Unable to unlink evidence.", locale)); } finally { setBusy(false); } }
  async function download(item: Evidence) { if (!workspaceId || busy) return; setBusy(true); setError(""); try { const data = await body<{ signedUrl?: string; error?: string }>(await fetch(`/api/evidence/${encodeURIComponent(item.id)}/download?workspaceId=${encodeURIComponent(workspaceId)}`)); if (!data.signedUrl) throw new Error("Signed download URL unavailable."); window.open(data.signedUrl, "_blank", "noopener,noreferrer"); } catch (cause) { setError(evidenceError(cause instanceof Error ? cause.message : "Unable to open evidence.", locale)); } finally { setBusy(false); } }
  async function replace() { if (!details || !file || !workspaceId || busy) return; setBusy(true); setError(""); try { const form = new FormData(); form.set("workspaceId", workspaceId); form.set("file", file); const result = await body<{ evidence?: Evidence; error?: string }>(await fetch(`/api/evidence/${encodeURIComponent(details.id)}/replace`, { method: "POST", body: form })); setDetails(result.evidence ?? details); setReplacing(false); setFile(null); await load(); } catch (cause) { setError(evidenceError(cause instanceof Error ? cause.message : "Unable to replace evidence.", locale)); } finally { setBusy(false); } }
  async function remove() { if (!details || !workspaceId || busy) return; setBusy(true); setError(""); try { await body(await fetch(`/api/evidence/${encodeURIComponent(details.id)}?workspaceId=${encodeURIComponent(workspaceId)}`, { method: "DELETE" })); setDetails(null); setDeleting(false); await load(); } catch (cause) { setError(evidenceError(cause instanceof Error ? cause.message : "Unable to delete evidence.", locale)); } finally { setBusy(false); } }
  function questionMeta(link: EvidenceLink) { const control = catalog[link.themeId].find((item) => item.id === link.controlId); const question = control?.questions.find((item) => item.id === link.questionId); return { control, question }; }

  return <main className={chrome.shell}>
    <AppSidebar organization={organization} workspaceId={workspaceId} />
    <section className={`${chrome.content} ${styles.content}`}><header className={chrome.topbar}><div className={chrome.crumb}><span>{organization}</span><b>/</b><strong>{locale === "fr" ? "Salle des preuves" : "Evidence Room"}</strong></div><div className={chrome.profileTools}><LanguageToggle className={chrome.language} /><span className={chrome.workspaceStatus}><i />{workspaceId ? (locale === "fr" ? "Espace actif" : "Workspace active") : (locale === "fr" ? "Configuration" : "Setup")}</span><span className={chrome.profileName}>{profile}</span><span className={chrome.avatar}>{profile.charAt(0).toUpperCase()}</span></div></header>
      <section className={styles.overview}><div className={styles.heading}><h1>{locale === "fr" ? "Salle des preuves" : "Evidence Room"}</h1><button type="button" className={styles.primary} disabled={!workspaceId} onClick={() => { resetUpload(); setUploadOpen(true); }}><Upload size={19} />{locale === "fr" ? "Importer une preuve" : "Upload evidence"}</button></div><div className={styles.kpis}><Kpi icon={<FileText />} label={locale === "fr" ? "Total des preuves" : "Total evidence"} value={metrics.total} /><Kpi icon={<Link2 />} label={locale === "fr" ? "Preuves liées" : "Linked evidence"} value={metrics.linked} tone="blue" /><Kpi icon={<Unlink />} label={locale === "fr" ? "Preuves non liées" : "Unlinked evidence"} value={metrics.unlinked} tone="red" /><Kpi icon={<File />} label={locale === "fr" ? "Questions avec preuves" : "Questions with evidence"} value={metrics.questions} tone="purple" /></div><div className={styles.filters}><label className={styles.search}><Search size={19} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={locale === "fr" ? "Rechercher une preuve" : "Search evidence"} /></label><select value={themeFilter} onChange={(event) => { setThemeFilter(event.target.value as Theme | ""); setControlFilter(""); }}><option value="">{locale === "fr" ? "Tous les thèmes" : "All themes"}</option>{themes.map((theme) => <option key={theme.value} value={theme.value}>{theme[locale]}</option>)}</select><select value={controlFilter} disabled={!themeFilter} onChange={(event) => setControlFilter(event.target.value)}><option value="">{locale === "fr" ? "Tous les contrôles" : "All controls"}</option>{controls.map((control) => <option key={control.id} value={control.id}>{control.code} — {control.title}</option>)}</select><select value={typeFilter} onChange={(event) => setTypeFilter(event.target.value)}><option value="">{locale === "fr" ? "Tous les types de fichiers" : "All file types"}</option>{["PDF", "PNG", "JPEG", "TXT", "CSV"].map((type) => <option key={type}>{type}</option>)}</select><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as "" | "linked" | "unlinked")}><option value="">{locale === "fr" ? "Tous les états de liaison" : "All link statuses"}</option><option value="linked">{locale === "fr" ? "Liée" : "Linked"}</option><option value="unlinked">{locale === "fr" ? "Non liée" : "Unlinked"}</option></select><button type="button" className={styles.clear} onClick={clearFilters}><FilterX size={18} />{locale === "fr" ? "Effacer les filtres" : "Clear filters"}</button></div></section>
      <section className={styles.library}><header><h2>{locale === "fr" ? "Bibliothèque de preuves" : "Evidence library"} <em>{filtered.length}</em></h2></header>{error && <p className={styles.error} role="alert">{error}</p>}<div className={styles.tableWrap}><table><thead><tr><th>{locale === "fr" ? "Preuve" : "Evidence"}</th><th>{locale === "fr" ? "Type" : "Type"}</th><th>{locale === "fr" ? "Taille" : "Size"}</th><th>{locale === "fr" ? "Importée par" : "Uploaded by"}</th><th>{locale === "fr" ? "Importée le" : "Uploaded"}</th><th>{locale === "fr" ? "Liée à" : "Linked to"}</th><th>{locale === "fr" ? "Actions" : "Actions"}</th></tr></thead><tbody>{loading ? <tr><td colSpan={7} className={styles.empty}><LoaderCircle className={styles.spin} />{locale === "fr" ? "Chargement des preuves…" : "Loading evidence…"}</td></tr> : visible.length ? visible.map((item) => { const count = links.filter((link) => link.evidenceId === item.id).length; return <tr key={item.id} tabIndex={0} onClick={() => setDetails(item)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setDetails(item); } }}><td><span className={`${styles.fileIcon} ${styles[kind(item).toLowerCase()]}`}>{iconFor(item)}</span><strong>{item.originalFilename}</strong></td><td>{kind(item)}</td><td>{formatSize(item.sizeBytes)}</td><td>{item.uploadedBy === profile ? profile : item.uploadedBy ? `${item.uploadedBy.slice(0, 8)}…` : "—"}</td><td>{formatDate(item.createdAt, locale)}</td><td>{count ? <span className={styles.linked}><Link2 size={17} />{count} {locale === "fr" ? `question${count > 1 ? "s" : ""}` : `question${count > 1 ? "s" : ""}`}</span> : <span className={styles.unlinked}>{locale === "fr" ? "Non liée" : "Unlinked"}</span>}</td><td><button type="button" className={styles.viewDetails} onClick={(event) => { event.stopPropagation(); setDetails(item); }}><ChevronRight size={17} />{locale === "fr" ? "Voir les détails" : "View details"}</button></td></tr>; }) : <tr><td colSpan={7} className={styles.empty}>{locale === "fr" ? "Aucune preuve pour le moment. Importez le premier fichier pour construire votre bibliothèque de preuves." : "No evidence yet. Upload the first file to build your evidence library."}</td></tr>}</tbody></table></div>{filtered.length > PAGE_SIZE && <Pagination page={page} pageCount={pageCount} onChange={setPage} locale={locale} />}</section>
    </section>
    {uploadOpen && <Modal title={locale === "fr" ? "Importer une preuve" : "Upload evidence"} close={() => !busy && setUploadOpen(false)} locale={locale}><button type="button" className={styles.dropzone} onClick={() => fileInput.current?.click()}><Upload size={25} /><strong>{locale === "fr" ? "Choisir un fichier" : "Choose a file"}</strong><span>PDF, PNG, JPEG, TXT, CSV · {locale === "fr" ? "Max." : "Max"} 10 MB</span></button><input ref={fileInput} className={styles.hidden} type="file" accept={ACCEPT} onChange={(event) => setFile(event.target.files?.[0] ?? null)} />{file && <SelectedFile file={file} clear={() => { setFile(null); if (fileInput.current) fileInput.current.value = ""; }} locale={locale} />}<hr /><div className={styles.modalSectionTitle}>{locale === "fr" ? "Lier à l’évaluation" : "Link to Assessment"} <small>{locale === "fr" ? "Facultatif" : "Optional"}</small><p>{locale === "fr" ? "Choisissez une question maintenant ou liez-la plus tard." : "Choose a question now, or link it later."}</p></div><CascadePicker value={cascade} onChange={setCascade} catalog={catalog} idPrefix="upload" locale={locale} /><footer className={styles.modalFooter}><button type="button" className={styles.textButton} disabled={busy} onClick={() => void upload()}>{locale === "fr" ? "Importer sans lier" : "Upload without linking"}</button><button type="button" className={styles.secondary} disabled={busy} onClick={() => setUploadOpen(false)}>{locale === "fr" ? "Annuler" : "Cancel"}</button><button type="button" className={styles.primary} disabled={!file || !cascade.questionId || busy} onClick={() => void upload()}>{busy ? (locale === "fr" ? "Importation…" : "Uploading…") : <><Link2 size={17} />{locale === "fr" ? "Importer et lier" : "Upload & link"}</>}</button></footer></Modal>}
    {details && <Modal title={locale === "fr" ? "Détails de la preuve" : "Evidence details"} close={() => !busy && setDetails(null)} locale={locale}>
      <div className={styles.detailFile}><span className={`${styles.fileIcon} ${styles[kind(details).toLowerCase()]}`}>{iconFor(details, 34)}</span><h2>{details.originalFilename}</h2><span className={detailLinks.length ? styles.statusLinked : styles.unlinked}>{detailLinks.length ? (locale === "fr" ? "Liée" : "Linked") : (locale === "fr" ? "Non liée" : "Unlinked")}</span></div>
      <div className={styles.metadata}><span>{locale === "fr" ? "Type de fichier" : "File type"}<b>{kind(details)}</b></span><span>{locale === "fr" ? "Importée par" : "Uploaded by"}<b>{details.uploadedBy ? `${details.uploadedBy.slice(0, 8)}…` : "—"}</b></span><span>{locale === "fr" ? "Taille" : "Size"}<b>{formatSize(details.sizeBytes)}</b></span><span>{locale === "fr" ? "Importée le" : "Uploaded at"}<b>{formatDate(details.createdAt, locale, true)}</b></span></div>
      {hasDocumentMetadata && <div className={`${styles.metadata} ${styles.documentMetadata}`}>
        {details.documentType && <span>{locale === "fr" ? "Type de document" : "Document type"}<b>{DOCUMENT_TYPE_LABELS[details.documentType]}</b></span>}
        {details.documentVersion && <span>Version<b>{details.documentVersion}</b></span>}
        {details.effectiveDate && <span>{locale === "fr" ? "Date d'entrée en vigueur" : "Effective date"}<b>{formatDate(details.effectiveDate, locale)}</b></span>}
        {details.reviewDate && <span>{locale === "fr" ? "Date de revue" : "Review date"}<b>{formatDate(details.reviewDate, locale)}</b></span>}
        {details.documentOwnerId && <span>{locale === "fr" ? "Propriétaire du document" : "Document owner"}<b>{documentOwner?.label ?? (locale === "fr" ? "Membre de l'espace" : "Workspace member")}</b></span>}
      </div>}
      <hr /><div className={styles.linkedTitle}>{locale === "fr" ? "Questions liées" : "Linked questions"} <em>{detailLinks.length}</em></div><div className={styles.questionLinks}>{detailLinks.map((link) => { const meta = questionMeta(link); return <article key={link.id}><FileText size={27} /><div><strong>{meta.control?.code ?? link.controlId} — {meta.control?.title ?? link.controlId}</strong><small>{themes.find((theme) => theme.value === link.themeId)?.[locale]}</small><p>{meta.question?.wording ?? link.questionId}</p></div><Link prefetch={true} href={`/assessment/${link.themeId}/${link.controlId}#${link.questionId}`}><Eye size={16} />{locale === "fr" ? "Voir le contrôle" : "View control"}</Link><button type="button" disabled={busy} onClick={() => void unlink(link)}><Unlink size={16} />{locale === "fr" ? "Délier" : "Unlink"}</button></article>; })}</div>{linking ? <div className={styles.inlineLink}><CascadePicker value={linkCascade} onChange={setLinkCascade} catalog={catalog} idPrefix="link" locale={locale} /><div><button type="button" className={styles.secondary} onClick={() => setLinking(false)}>{locale === "fr" ? "Annuler" : "Cancel"}</button><button type="button" className={styles.primary} disabled={!linkCascade.questionId || busy} onClick={() => void addLink()}><Link2 size={16} />{locale === "fr" ? "Lier la question" : "Link question"}</button></div></div> : <button type="button" className={styles.addLink} onClick={() => { setLinkCascade(emptyCascade()); setLinking(true); }}><Plus size={20} />{locale === "fr" ? "Lier à une autre question" : "Link to another question"} <small>{locale === "fr" ? "Ajoute une liaison sans dupliquer le fichier." : "Adds a link without duplicating the file."}</small></button>}<footer className={styles.detailFooter}><button type="button" onClick={() => void download(details)}><Eye size={17} />{locale === "fr" ? "Voir" : "View"}</button><button type="button" onClick={() => void download(details)}><Download size={17} />{locale === "fr" ? "Télécharger" : "Download"}</button><button type="button" onClick={() => { setFile(null); setReplacing(true); }}><Replace size={17} />{locale === "fr" ? "Remplacer le fichier" : "Replace file"}</button><button type="button" className={styles.danger} onClick={() => setDeleting(true)}><Trash2 size={17} />{locale === "fr" ? "Supprimer la preuve" : "Delete evidence"}</button></footer>
    </Modal>}
    {replacing && details && <Modal title={locale === "fr" ? "Remplacer le fichier" : "Replace file"} close={() => !busy && setReplacing(false)} locale={locale}><p className={styles.confirmText}>{locale === "fr" ? "L'identité de la preuve et toutes les questions liées existantes seront conservées." : "The evidence identity and all existing question links will be preserved."}</p><button type="button" className={styles.dropzone} onClick={() => replaceInput.current?.click()}><Replace size={24} /><strong>{locale === "fr" ? "Choisir un fichier de remplacement" : "Choose replacement file"}</strong><span>PDF, PNG, JPEG, TXT, CSV · {locale === "fr" ? "Max." : "Max"} 10 MB</span></button><input ref={replaceInput} className={styles.hidden} type="file" accept={ACCEPT} onChange={(event) => setFile(event.target.files?.[0] ?? null)} />{file && <SelectedFile file={file} clear={() => setFile(null)} locale={locale} />}<footer className={styles.modalFooter}><button type="button" className={styles.secondary} onClick={() => setReplacing(false)}>{locale === "fr" ? "Annuler" : "Cancel"}</button><button type="button" className={styles.primary} disabled={!file || busy} onClick={() => void replace()}>{busy ? (locale === "fr" ? "Remplacement…" : "Replacing…") : (locale === "fr" ? "Remplacer le fichier" : "Replace file")}</button></footer></Modal>}
    {deleting && details && <Modal title={locale === "fr" ? "Supprimer la preuve" : "Delete evidence"} close={() => !busy && setDeleting(false)} locale={locale}><p className={styles.confirmText}>{locale === "fr" ? "Cette action supprime le fichier et toutes ses questions liées. Elle ne peut pas être annulée." : "This deletes the file and all of its linked questions. This action cannot be undone."}</p><footer className={styles.modalFooter}><button type="button" className={styles.secondary} onClick={() => setDeleting(false)}>{locale === "fr" ? "Annuler" : "Cancel"}</button><button type="button" className={styles.deleteButton} disabled={busy} onClick={() => void remove()}>{busy ? (locale === "fr" ? "Suppression…" : "Deleting…") : (locale === "fr" ? "Supprimer la preuve" : "Delete evidence")}</button></footer></Modal>}
  </main>;
}

function Kpi({ icon, label, value, tone = "aqua" }: { icon: React.ReactNode; label: string; value: number; tone?: string }) { return <article className={`${styles.kpi} ${styles[tone]}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></article>; }
function SelectedFile({ file, clear, locale }: { file: File; clear: () => void; locale: "en" | "fr" }) { const item = { mimeType: file.type, originalFilename: file.name }; return <div className={styles.selectedFile}><span className={`${styles.fileIcon} ${styles[kind(item).toLowerCase()]}`}>{iconFor(item)}</span><div><strong>{file.name}</strong><small>{kind(item)} · {formatSize(file.size)}</small></div><button type="button" onClick={clear} aria-label={locale === "fr" ? "Retirer le fichier sélectionné" : "Remove selected file"}><X size={19} /></button></div>; }
function Modal({ title, close, children, locale }: { title: string; close: () => void; children: React.ReactNode; locale: "en" | "fr" }) { return <div className={styles.overlay} role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) close(); }}><section className={styles.modal} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button type="button" aria-label={locale === "fr" ? "Fermer" : "Close"} onClick={close}><X size={22} /></button></header>{children}</section></div>; }
function Pagination({ page, pageCount, onChange, locale }: { page: number; pageCount: number; onChange: (page: number) => void; locale: "en" | "fr" }) { return <nav className={styles.pagination} aria-label={locale === "fr" ? "Pages des preuves" : "Evidence pages"}><button type="button" disabled={page === 1} onClick={() => onChange(page - 1)}><ChevronLeft /></button>{Array.from({ length: pageCount }, (_, index) => <button type="button" className={page === index + 1 ? styles.currentPage : ""} key={index} onClick={() => onChange(index + 1)}>{index + 1}</button>)}<button type="button" disabled={page === pageCount} onClick={() => onChange(page + 1)}><ChevronRight /></button></nav>; }
