export const authCopy = {
  en: {
    back: "Back",
    fullName: "Full name",
    fullNamePlaceholder: "Alex Morgan",
    workEmail: "Work email",
    emailPlaceholder: "alex@company.com",
    password: "Password",
    confirmPassword: "Confirm password",
    createPasswordPlaceholder: "Create a secure password",
    passwordPlaceholder: "Enter your password",
    confirmationPlaceholder: "Repeat your password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    showConfirmation: "Show password confirmation",
    hideConfirmation: "Hide password confirmation",
    remember: "Remember me",
    termsPrefix: "I agree to the",
    terms: "Terms",
    termsAnd: "and",
    privacy: "Privacy Policy",
    forgot: "Forgot password?",
    mismatch: "Passwords do not match.",
    or: "OR",
    already: "Already have an account?",
    newUser: "New to NormCore?",
    signIn: "Sign in",
    createAccount: "Create an account",
    trust: "Readiness, not certification. AI assists; people remain in control.",
    configurationMissing: "Supabase Auth is not configured yet. Add the public project URL and publishable key to .env.local.",
    genericError: "We couldn’t complete this request. Please try again.",
    invalidCredentials: "The email or password is incorrect.",
    emailNotConfirmed: "Confirm your email address before signing in.",
    tooManyRequests: "Too many attempts. Please wait before trying again.",
    weakPassword: "Choose a stronger password with at least 8 characters.",
    accountExists: "An account may already exist for this email. Try signing in or resetting your password.",
    sessionExpired: "Your secure session has expired. Please start again.",
    login: {
      title: "Welcome back",
      description: "Sign in to continue your Annex A readiness work.",
      submitLabel: "Sign in",
      success: "Signed in successfully. Your secure session is active.",
      verified: "Your email is verified. You can now sign in.",
    },
    signup: {
      title: "Create your account",
      description: "Start your guided Annex A readiness assessment.",
      submitLabel: "Create account",
    },
    forgotPassword: {
      title: "Forgot your password?",
      description: "Enter your work email and we’ll send you a secure password reset code.",
      submitLabel: "Send reset code",
      back: "Back to Login",
    },
    checkEmail: {
      title: "Check your email",
      signupDescription: "We sent a verification code to",
      recoveryDescription: "We sent a password reset code to",
      instruction: "Enter the code below to continue.",
      codeLabel: "Verification code",
      codePlaceholder: "Enter the code",
      verifySignup: "Verify email",
      verifyRecovery: "Verify code",
      invalidCode: "The code is invalid or has expired.",
      resend: "Resend code",
      resendIn: "Resend in {seconds}s",
      resent: "A new code has been sent.",
      back: "Back to Login",
      changeEmail: "Use a different email",
    },
    setPassword: {
      title: "Set a new password",
      description: "Choose a new secure password for your NormCore account.",
      newPassword: "New password",
      submitLabel: "Update password",
    },
    passwordUpdated: {
      title: "Password updated",
      description: "Your password has been changed successfully. You can now sign in with your new password.",
      button: "Return to Login",
    },
  },
  fr: {
    back: "Retour",
    fullName: "Nom complet",
    fullNamePlaceholder: "Alex Morgan",
    workEmail: "E-mail professionnel",
    emailPlaceholder: "alex@entreprise.com",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    createPasswordPlaceholder: "Créez un mot de passe sécurisé",
    passwordPlaceholder: "Saisissez votre mot de passe",
    confirmationPlaceholder: "Répétez votre mot de passe",
    showPassword: "Afficher le mot de passe",
    hidePassword: "Masquer le mot de passe",
    showConfirmation: "Afficher la confirmation du mot de passe",
    hideConfirmation: "Masquer la confirmation du mot de passe",
    remember: "Se souvenir de moi",
    termsPrefix: "J’accepte les",
    terms: "Conditions d’utilisation",
    termsAnd: "et la",
    privacy: "Politique de confidentialité",
    forgot: "Mot de passe oublié ?",
    mismatch: "Les mots de passe ne correspondent pas.",
    or: "OU",
    already: "Vous avez déjà un compte ?",
    newUser: "Nouveau sur NormCore ?",
    signIn: "Se connecter",
    createAccount: "Créer un compte",
    trust: "Préparation, pas certification. L’IA assiste ; les personnes gardent le contrôle.",
    configurationMissing: "Supabase Auth n’est pas encore configuré. Ajoutez l’URL publique du projet et la clé publishable dans .env.local.",
    genericError: "Nous n’avons pas pu terminer cette demande. Veuillez réessayer.",
    invalidCredentials: "L’e-mail ou le mot de passe est incorrect.",
    emailNotConfirmed: "Confirmez votre adresse e-mail avant de vous connecter.",
    tooManyRequests: "Trop de tentatives. Veuillez patienter avant de réessayer.",
    weakPassword: "Choisissez un mot de passe plus robuste contenant au moins 8 caractères.",
    accountExists: "Un compte existe peut-être déjà pour cet e-mail. Essayez de vous connecter ou de réinitialiser votre mot de passe.",
    sessionExpired: "Votre session sécurisée a expiré. Veuillez recommencer.",
    login: {
      title: "Bon retour",
      description: "Connectez-vous pour poursuivre votre préparation à l’Annexe A.",
      submitLabel: "Se connecter",
      success: "Connexion réussie. Votre session sécurisée est active.",
      verified: "Votre e-mail est vérifié. Vous pouvez maintenant vous connecter.",
    },
    signup: {
      title: "Créez votre compte",
      description: "Commencez votre évaluation guidée de préparation à l’Annexe A.",
      submitLabel: "Créer un compte",
    },
    forgotPassword: {
      title: "Mot de passe oublié ?",
      description: "Saisissez votre e-mail professionnel et nous vous enverrons un code sécurisé de réinitialisation.",
      submitLabel: "Envoyer le code",
      back: "Retour à la connexion",
    },
    checkEmail: {
      title: "Consultez votre e-mail",
      signupDescription: "Nous avons envoyé un code de vérification à",
      recoveryDescription: "Nous avons envoyé un code de réinitialisation à",
      instruction: "Saisissez le code ci-dessous pour continuer.",
      codeLabel: "Code de vérification",
      codePlaceholder: "Saisissez le code",
      verifySignup: "Vérifier l’e-mail",
      verifyRecovery: "Vérifier le code",
      invalidCode: "Le code est incorrect ou a expiré.",
      resend: "Renvoyer le code",
      resendIn: "Renvoyer dans {seconds}s",
      resent: "Un nouveau code a été envoyé.",
      back: "Retour à la connexion",
      changeEmail: "Utiliser un autre e-mail",
    },
    setPassword: {
      title: "Définir un nouveau mot de passe",
      description: "Choisissez un nouveau mot de passe sécurisé pour votre compte NormCore.",
      newPassword: "Nouveau mot de passe",
      submitLabel: "Mettre à jour le mot de passe",
    },
    passwordUpdated: {
      title: "Mot de passe mis à jour",
      description: "Votre mot de passe a été modifié. Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.",
      button: "Retour à la connexion",
    },
  },
} as const;

export type AuthLanguage = keyof typeof authCopy;
