import type { ScreeningAnswerValue } from "./outcomes.ts";
import { deriveAssessmentOutcome } from "./outcomes.ts";
import { type SecureDisposalReuseQuestionId, type SecureDisposalReuseQuestion, secureDisposalReuseQuestions, A7_14_SECURE_DISPOSAL_REUSE_PLAN, A7_14_SECURE_DISPOSAL_REUSE_GAP_CODES } from "../../content/assessment/physical/secure-disposal-reuse.ts";
type LocalizedText = { fr: string; en: string }; type Priority = "medium" | "high";
export type A714ResponseInput = { questionId: SecureDisposalReuseQuestionId; answer: ScreeningAnswerValue; hasEvidence?: boolean; justification?: string; evidenceStatus?: Parameters<typeof deriveAssessmentOutcome>[0]["evidenceStatus"] };
export type A714ResolutionResult = { controlApplicability: "applicable"; controlReviewState: "none"; requiresControlJustification: false; questionIds: SecureDisposalReuseQuestionId[]; hiddenQuestionIds: SecureDisposalReuseQuestionId[]; unresolvedConditions: string[]; assessmentBlocked: false };
type Action = { actionCode: string; sourceQuestionId: SecureDisposalReuseQuestionId; partialTitle: LocalizedText; fullTitle: LocalizedText; partialDescription: LocalizedText; fullDescription: LocalizedText; recommendedActions: LocalizedText; closureCriteria: LocalizedText; partialPriority: Priority; fullPriority: Priority; partialGapCode: string; fullGapCode: string };
export type A714DerivedSubAction = Action & { status: "active"; gapType: "partial" | "full"; gapCode: string; priority: Priority };
export function resolveSecureDisposalReuseQuestions(): A714ResolutionResult { return { controlApplicability: "applicable", controlReviewState: "none", requiresControlJustification: false, questionIds: ["p7_14_001", "p7_14_002", "p7_14_003"], hiddenQuestionIds: [], unresolvedConditions: [], assessmentBlocked: false }; }
const actions: Record<string, Action> = {
  "P7.14-A01": { actionCode: "P7.14-A01", sourceQuestionId: "p7_14_001", partialTitle: { fr: "Règles incomplètes", en: "Incomplete rules" }, fullTitle: { fr: "Absence de règles", en: "No rules" }, partialDescription: { fr: "Le processus existe mais certains équipements, chemins, responsabilités ou logiciels ne sont pas couverts.", en: "The process exists but some equipment, paths, responsibilities, or software are not covered." }, fullDescription: { fr: "Des équipements sont éliminés ou réaffectés sans processus de sécurisation défini.", en: "Equipment is disposed of or reassigned without a defined security process." }, recommendedActions: { fr: "- compléter le processus et les chemins de sortie manquants ;\n- identifier équipements, événements, données, logiciels, responsables et méthodes appropriées.", en: "- complete the process and missing exit paths;\n- identify equipment, events, data, software, responsibilities, and appropriate methods." }, closureCriteria: { fr: "Les équipements et chemins pertinents sont couverts par un processus proportionné.", en: "Relevant equipment and paths are covered by a proportionate process." }, partialPriority: "medium", fullPriority: "high", partialGapCode: A7_14_SECURE_DISPOSAL_REUSE_GAP_CODES.A7_14_DISPOSAL_REUSE_RULES_PARTIAL, fullGapCode: A7_14_SECURE_DISPOSAL_REUSE_GAP_CODES.A7_14_DISPOSAL_REUSE_RULES_ABSENT },
  "P7.14-A02": { actionCode: "P7.14-A02", sourceQuestionId: "p7_14_002", partialTitle: { fr: "Vérification incomplète", en: "Incomplete verification" }, fullTitle: { fr: "Absence de vérification", en: "No verification" }, partialDescription: { fr: "La sanitization est généralement réalisée mais certains équipements, scénarios, méthodes ou vérifications présentent des lacunes.", en: "Sanitization is generally performed but some equipment, scenarios, methods, or verifications have gaps." }, fullDescription: { fr: "Des équipements peuvent sortir ou être réutilisés sans vérification fiable du traitement des données et logiciels.", en: "Equipment can leave or be reused without reliable verification of data and software handling." }, recommendedActions: { fr: "- traiter les équipements ou scénarios manquants ;\n- vérifier l’efficacité des méthodes adaptées au support et au risque.", en: "- address missing equipment or scenarios;\n- verify the effectiveness of methods appropriate to media and risk." }, closureCriteria: { fr: "La vérification avant sortie ou réaffectation est effective et proportionnée.", en: "Pre-release or reassignment verification is effective and proportionate." }, partialPriority: "high", fullPriority: "high", partialGapCode: A7_14_SECURE_DISPOSAL_REUSE_GAP_CODES.A7_14_SANITIZATION_VERIFICATION_PARTIAL, fullGapCode: A7_14_SECURE_DISPOSAL_REUSE_GAP_CODES.A7_14_SANITIZATION_VERIFICATION_ABSENT },
  "P7.14-A03": { actionCode: "P7.14-A03", sourceQuestionId: "p7_14_003", partialTitle: { fr: "Traçabilité incomplète", en: "Incomplete traceability" }, fullTitle: { fr: "Absence de preuve", en: "No evidence" }, partialDescription: { fr: "Le traitement est réalisé mais certaines preuves, vérifications, équipements ou opérations tierces ne sont pas suffisamment traçables.", en: "Processing occurs but some evidence, verification, equipment, or third-party activity is insufficiently traceable." }, fullDescription: { fr: "Aucun moyen fiable ne démontre qu’un équipement éliminé ou réutilisé a été sécurisé.", en: "No reliable means demonstrates that disposed or reused equipment was secured." }, recommendedActions: { fr: "- compléter les enregistrements ;\n- relier l’équipement à la décision, méthode, vérification, tiers, exception et clôture.", en: "- complete records;\n- link equipment to decision, method, verification, third party, exception, and closure." }, closureCriteria: { fr: "Une piste de preuve proportionnée relie les éléments pertinents à leur clôture.", en: "Proportionate evidence links relevant elements to closure." }, partialPriority: "medium", fullPriority: "high", partialGapCode: A7_14_SECURE_DISPOSAL_REUSE_GAP_CODES.A7_14_DISPOSAL_REUSE_TRACEABILITY_PARTIAL, fullGapCode: A7_14_SECURE_DISPOSAL_REUSE_GAP_CODES.A7_14_DISPOSAL_REUSE_TRACEABILITY_ABSENT },
};
const actionByQuestion = new Map<SecureDisposalReuseQuestionId, Action>(Object.values(actions).map(a => [a.sourceQuestionId, a])); const known = new Map<SecureDisposalReuseQuestionId, SecureDisposalReuseQuestion>(secureDisposalReuseQuestions.map(q => [q.id, q]));
export function deriveSecureDisposalReuseOutcome(responses: A714ResponseInput[], resolution: A714ResolutionResult): { reviewState: string; gapActions: A714DerivedSubAction[] } { const latest = new Map<SecureDisposalReuseQuestionId, A714ResponseInput>(); for (const r of responses) if (known.has(r.questionId)) latest.set(r.questionId, r); let reviewState: string = resolution.controlReviewState; const active = new Map<string, A714DerivedSubAction>(); for (const r of latest.values()) { const outcome = deriveAssessmentOutcome({ ...r, hasEvidence: Boolean(r.hasEvidence) }); if (!outcome.isValid) { reviewState = "applicability_review_required"; continue; } if (outcome.reviewState !== "none") reviewState = outcome.reviewState; if (outcome.createsGapAction === "none") continue; const a = actionByQuestion.get(r.questionId); if (!a) continue; const gapType = outcome.createsGapAction === "partial" ? "partial" : "full"; active.set(a.actionCode, { ...a, status: "active", gapType, gapCode: gapType === "partial" ? a.partialGapCode : a.fullGapCode, priority: gapType === "partial" ? a.partialPriority : a.fullPriority }); } return { reviewState, gapActions: [...active.values()] }; }
export function deriveSecureDisposalReuseRemediationPlan(outcome: { reviewState: string; gapActions: A714DerivedSubAction[] }) { if (!outcome.gapActions.length) return []; return [{ planCode: A7_14_SECURE_DISPOSAL_REUSE_PLAN, actions: outcome.gapActions.map(a => ({ actionCode: a.actionCode, title: a.gapType === "partial" ? a.partialTitle : a.fullTitle, description: a.gapType === "partial" ? a.partialDescription : a.fullDescription, priority: a.priority, remediationSteps: a.recommendedActions, closureCriteria: a.closureCriteria })) }]; }
