ONBOARDING_SCHEMA_VERSION = "1.0"


def _question(
    identifier: str,
    step: int,
    label: str,
    field_type: str,
    required: bool,
    destination: str,
    options: list[str] | None = None,
    conditional_rules: list[dict[str, object]] | None = None,
) -> dict[str, object]:
    return {
        "id": identifier,
        "step": step,
        "label": label,
        "field_type": field_type,
        "required": required,
        "options": options or [],
        "conditional_rules": conditional_rules or [],
        "destination": destination,
    }


ONBOARDING_CATALOG = {
    "schema_version": ONBOARDING_SCHEMA_VERSION,
    "steps": [
        {
            "id": 1,
            "label": "Activité et processus",
            "questions": [
                _question(
                    "activity",
                    1,
                    "Activité, produit ou service concerné",
                    "activity",
                    True,
                    "organization_activities",
                    [
                        "web_application_saas",
                        "it_services_managed_services",
                        "consulting_professional_services",
                        "ecommerce",
                        "software_development",
                        "hosting_operations",
                        "customer_support",
                        "data_processing",
                        "internal_business_activity",
                        "other",
                    ],
                ),
                _question(
                    "critical_processes",
                    1,
                    "Processus critiques",
                    "multi_select_with_custom",
                    True,
                    "organization_processes",
                    [
                        "main_product_or_service",
                        "customer_support",
                        "software_development",
                        "infrastructure_hosting",
                        "billing_payment",
                        "human_resources_payroll",
                        "sales_crm",
                        "delivery_operations",
                        "other",
                    ],
                ),
            ],
        },
        {
            "id": 2,
            "label": "Organisation et technologies",
            "questions": [
                _question(
                    "teams",
                    2,
                    "Équipes ou fonctions concernées",
                    "multi_select_with_custom",
                    True,
                    "organization_teams",
                    [
                        "executive_management",
                        "it",
                        "security",
                        "infrastructure_devops",
                        "software_development",
                        "customer_support",
                        "sales",
                        "human_resources",
                        "finance",
                        "legal_compliance",
                        "operations",
                        "external_contractors",
                        "whole_organization",
                        "other",
                    ],
                ),
                _question(
                    "work_sites_contractors",
                    2,
                    "Mode de travail, sites et prestataires réguliers",
                    "compound",
                    True,
                    "organization_profiles,organization_sites",
                    ["onsite", "hybrid", "mainly_remote", "fully_remote"],
                    [
                        {
                            "when": {"multiple_sites_status": "yes"},
                            "requires": ["sites"],
                        }
                    ],
                ),
                _question(
                    "systems",
                    2,
                    "Systèmes principaux",
                    "compound",
                    True,
                    "organization_profiles,organization_systems",
                    [
                        "business_application",
                        "website_customer_portal",
                        "database",
                        "professional_email",
                        "document_storage",
                        "crm",
                        "erp_accounting",
                        "hr_payroll",
                        "source_code_repository",
                        "customer_support_tool",
                        "cloud_infrastructure",
                        "internal_servers",
                        "other",
                        "no_critical_system_identified",
                        "unknown",
                    ],
                ),
                _question(
                    "hosting",
                    2,
                    "Modèle d’hébergement",
                    "multi_select",
                    True,
                    "organization_profiles",
                    [
                        "public_cloud",
                        "private_cloud",
                        "dedicated_hosting",
                        "internal_servers",
                        "mainly_third_party_saas",
                        "hybrid",
                        "unknown",
                    ],
                    [
                        {
                            "when_any": [
                                "public_cloud",
                                "private_cloud",
                                "mainly_third_party_saas",
                                "hybrid",
                            ],
                            "allows": ["selected_cloud_providers"],
                        }
                    ],
                ),
            ],
        },
        {
            "id": 3,
            "label": "Informations et dépendances",
            "questions": [
                _question(
                    "data_categories",
                    3,
                    "Catégories d’informations traitées",
                    "compound",
                    True,
                    "organization_data_categories,organization_profiles",
                    [
                        "customer_data",
                        "personal_data",
                        "employee_data",
                        "financial_data",
                        "payment_data",
                        "health_data",
                        "minors_data",
                        "customer_confidential_information",
                        "source_code",
                        "intellectual_property",
                        "credentials_and_technical_secrets",
                        "technical_logs",
                        "contracts",
                        "other",
                        "unknown",
                    ],
                ),
                _question(
                    "critical_suppliers",
                    3,
                    "Fournisseurs critiques",
                    "compound",
                    True,
                    "organization_suppliers,organization_profiles",
                    ["identified", "none_identified", "unknown"],
                    [{"when": {"status": "identified"}, "requires": ["suppliers"]}],
                ),
                _question(
                    "external_requirements",
                    3,
                    "Exigences externes connues",
                    "multi_select_with_details",
                    False,
                    "organization_external_requirements",
                    [
                        "customer_iso27001_request",
                        "data_protection_gdpr",
                        "nis2",
                        "dora",
                        "pci_dss",
                        "soc2",
                        "contractual_security_requirements",
                        "data_residency",
                        "health_finance_public_sector_requirement",
                        "other",
                        "none_known",
                        "unknown",
                    ],
                ),
            ],
        },
    ],
}
