"""add onboarding and isms scope

Revision ID: 703af0b528b7
Revises: a85651f7acaf
Create Date: 2026-07-24 22:25:23.630139
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '703af0b528b7'
down_revision: str | None = 'a85651f7acaf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('started_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'pending_review', 'validated', 'archived')", name='ck_onboarding_sessions_status'),
    sa.CheckConstraint('completion_percentage BETWEEN 0 AND 100', name='ck_onboarding_sessions_completion_percentage'),
    sa.CheckConstraint('current_step BETWEEN 1 AND 3', name='ck_onboarding_sessions_current_step'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'version', name='uq_onboarding_sessions_org_version')
    )
    op.create_index(op.f('ix_onboarding_sessions_organization_id'), 'onboarding_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_onboarding_sessions_started_by_user_id'), 'onboarding_sessions', ['started_by_user_id'], unique=False)
    op.create_index(op.f('ix_onboarding_sessions_validated_by_user_id'), 'onboarding_sessions', ['validated_by_user_id'], unique=False)
    op.create_index('uq_onboarding_sessions_active_org', 'onboarding_sessions', ['organization_id'], unique=True, postgresql_where=sa.text("status IN ('draft', 'pending_review')"))
    op.create_table('isms_scopes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('based_on_onboarding_session_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('validated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'pending_review', 'validated', 'archived')", name='ck_isms_scopes_status'),
    sa.ForeignKeyConstraint(['based_on_onboarding_session_id'], ['onboarding_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'version', name='uq_isms_scopes_org_version')
    )
    op.create_index(op.f('ix_isms_scopes_based_on_onboarding_session_id'), 'isms_scopes', ['based_on_onboarding_session_id'], unique=False)
    op.create_index(op.f('ix_isms_scopes_organization_id'), 'isms_scopes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_isms_scopes_owner_user_id'), 'isms_scopes', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_isms_scopes_validated_by_user_id'), 'isms_scopes', ['validated_by_user_id'], unique=False)
    op.create_index('uq_isms_scopes_active_org', 'isms_scopes', ['organization_id'], unique=True, postgresql_where=sa.text("status IN ('draft', 'pending_review')"))
    op.create_table('organization_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_session_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('nature_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onboarding_session_id', 'name', name='uq_organization_activities_session_name')
    )
    op.create_index(op.f('ix_organization_activities_onboarding_session_id'), 'organization_activities', ['onboarding_session_id'], unique=False)
    op.create_index(op.f('ix_organization_activities_organization_id'), 'organization_activities', ['organization_id'], unique=False)
    op.create_table('organization_data_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_session_id', sa.Uuid(), nullable=False),
    sa.Column('category_type', sa.String(length=80), nullable=False),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onboarding_session_id', 'category_type', 'custom_name', name='uq_organization_data_categories_session_value')
    )
    op.create_index(op.f('ix_organization_data_categories_onboarding_session_id'), 'organization_data_categories', ['onboarding_session_id'], unique=False)
    op.create_index(op.f('ix_organization_data_categories_organization_id'), 'organization_data_categories', ['organization_id'], unique=False)
    op.create_table('organization_external_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_session_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_type', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('confirmation_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confirmation_status IN ('declared_to_confirm', 'confirmed', 'not_applicable')", name='ck_organization_external_requirements_status'),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onboarding_session_id', 'requirement_type', 'details', name='uq_organization_external_requirements_session_value')
    )
    op.create_index(op.f('ix_organization_external_requirements_onboarding_session_id'), 'organization_external_requirements', ['onboarding_session_id'], unique=False)
    op.create_index(op.f('ix_organization_external_requirements_organization_id'), 'organization_external_requirements', ['organization_id'], unique=False)
    op.create_table('organization_processes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_session_id', sa.Uuid(), nullable=False),
    sa.Column('process_type', sa.String(length=80), nullable=False),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onboarding_session_id', 'process_type', 'custom_name', name='uq_organization_processes_session_value')
    )
    op.create_index(op.f('ix_organization_processes_onboarding_session_id'), 'organization_processes', ['onboarding_session_id'], unique=False)
    op.create_index(op.f('ix_organization_processes_organization_id'), 'organization_processes', ['organization_id'], unique=False)
    op.create_table('organization_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_session_id', sa.Uuid(), nullable=False),
    sa.Column('work_mode', sa.String(length=30), nullable=True),
    sa.Column('multiple_sites_status', sa.String(length=20), nullable=True),
    sa.Column('regular_external_contractors_status', sa.String(length=20), nullable=True),
    sa.Column('hosting_models', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_cloud_providers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('highest_sensitivity_level', sa.String(length=30), nullable=True),
    sa.Column('system_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('systems_identification_status', sa.String(length=40), nullable=True),
    sa.Column('suppliers_identification_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("multiple_sites_status IS NULL OR multiple_sites_status IN ('yes', 'no', 'unknown')", name='ck_organization_profiles_multiple_sites'),
    sa.CheckConstraint("regular_external_contractors_status IS NULL OR regular_external_contractors_status IN ('yes', 'no', 'unknown')", name='ck_organization_profiles_contractors'),
    sa.CheckConstraint("suppliers_identification_status IS NULL OR suppliers_identification_status IN ('identified', 'none_identified', 'unknown')", name='ck_organization_profiles_suppliers_status'),
    sa.CheckConstraint("work_mode IS NULL OR work_mode IN ('onsite', 'hybrid', 'mainly_remote', 'fully_remote')", name='ck_organization_profiles_work_mode'),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onboarding_session_id', name='uq_organization_profiles_session')
    )
    op.create_index(op.f('ix_organization_profiles_onboarding_session_id'), 'organization_profiles', ['onboarding_session_id'], unique=False)
    op.create_index(op.f('ix_organization_profiles_organization_id'), 'organization_profiles', ['organization_id'], unique=False)
    op.create_table('organization_sites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_session_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('site_type', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onboarding_session_id', 'name', 'city', 'country', name='uq_organization_sites_session_location')
    )
    op.create_index(op.f('ix_organization_sites_onboarding_session_id'), 'organization_sites', ['onboarding_session_id'], unique=False)
    op.create_index(op.f('ix_organization_sites_organization_id'), 'organization_sites', ['organization_id'], unique=False)
    op.create_table('organization_suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_session_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('supplier_type', sa.String(length=80), nullable=False),
    sa.Column('related_service_or_system', sa.String(length=255), nullable=True),
    sa.Column('processes_or_hosts_data', sa.String(length=20), nullable=False),
    sa.Column('has_system_access', sa.String(length=20), nullable=False),
    sa.Column('criticality', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("criticality IN ('low', 'medium', 'high', 'to_determine')", name='ck_organization_suppliers_criticality'),
    sa.CheckConstraint("has_system_access IN ('yes', 'no', 'unknown')", name='ck_organization_suppliers_system_access'),
    sa.CheckConstraint("processes_or_hosts_data IN ('yes', 'no', 'unknown')", name='ck_organization_suppliers_processes_data'),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onboarding_session_id', 'name', name='uq_organization_suppliers_session_name')
    )
    op.create_index(op.f('ix_organization_suppliers_onboarding_session_id'), 'organization_suppliers', ['onboarding_session_id'], unique=False)
    op.create_index(op.f('ix_organization_suppliers_organization_id'), 'organization_suppliers', ['organization_id'], unique=False)
    op.create_table('organization_systems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_session_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('system_type', sa.String(length=80), nullable=False),
    sa.Column('supported_activity_or_process', sa.String(length=255), nullable=True),
    sa.Column('provider_or_host', sa.String(length=255), nullable=True),
    sa.Column('identification_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("identification_status IN ('identified', 'to_determine')", name='ck_organization_systems_identification_status'),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onboarding_session_id', 'name', 'system_type', name='uq_organization_systems_session_name_type')
    )
    op.create_index(op.f('ix_organization_systems_onboarding_session_id'), 'organization_systems', ['onboarding_session_id'], unique=False)
    op.create_index(op.f('ix_organization_systems_organization_id'), 'organization_systems', ['organization_id'], unique=False)
    op.create_table('organization_teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_session_id', sa.Uuid(), nullable=False),
    sa.Column('team_type', sa.String(length=80), nullable=False),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onboarding_session_id', 'team_type', 'custom_name', name='uq_organization_teams_session_value')
    )
    op.create_index(op.f('ix_organization_teams_onboarding_session_id'), 'organization_teams', ['onboarding_session_id'], unique=False)
    op.create_index(op.f('ix_organization_teams_organization_id'), 'organization_teams', ['organization_id'], unique=False)
    op.create_table('scope_elements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=False),
    sa.Column('source_onboarding_session_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('element_type', sa.String(length=40), nullable=False),
    sa.Column('element_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('capiso_suggestion', sa.String(length=40), nullable=False),
    sa.Column('suggestion_reason', sa.Text(), nullable=False),
    sa.Column('user_decision', sa.String(length=30), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("capiso_suggestion IN ('include_recommended', 'review_required', 'insufficient_information', 'link_not_identified')", name='ck_scope_elements_suggestion'),
    sa.CheckConstraint("element_type IN ('activity', 'process', 'team', 'site', 'system', 'data_category', 'supplier', 'hosting')", name='ck_scope_elements_element_type'),
    sa.CheckConstraint("source_type IN ('activity', 'process', 'team', 'site', 'system', 'data_category', 'supplier', 'hosting')", name='ck_scope_elements_source_type'),
    sa.CheckConstraint("status IN ('pending', 'validated', 'needs_clarification')", name='ck_scope_elements_status'),
    sa.CheckConstraint("user_decision IN ('include', 'exclude', 'to_determine')", name='ck_scope_elements_decision'),
    sa.ForeignKeyConstraint(['scope_id'], ['isms_scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_onboarding_session_id'], ['onboarding_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'source_type', 'source_id', name='uq_scope_elements_scope_source')
    )
    op.create_index(op.f('ix_scope_elements_scope_id'), 'scope_elements', ['scope_id'], unique=False)
    op.create_index(op.f('ix_scope_elements_source_onboarding_session_id'), 'scope_elements', ['source_onboarding_session_id'], unique=False)
    op.create_table('scope_clarifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=False),
    sa.Column('scope_element_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution_comment', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('todo', 'in_progress', 'resolved', 'cancelled')", name='ck_scope_clarifications_status'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scope_element_id'], ['scope_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_id'], ['isms_scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_clarifications_assigned_to_user_id'), 'scope_clarifications', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_scope_clarifications_organization_id'), 'scope_clarifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scope_clarifications_scope_element_id'), 'scope_clarifications', ['scope_element_id'], unique=False)
    op.create_index(op.f('ix_scope_clarifications_scope_id'), 'scope_clarifications', ['scope_id'], unique=False)
    op.create_index('uq_scope_clarifications_open_element', 'scope_clarifications', ['scope_element_id'], unique=True, postgresql_where=sa.text("status IN ('todo', 'in_progress')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_scope_clarifications_open_element', table_name='scope_clarifications', postgresql_where=sa.text("status IN ('todo', 'in_progress')"))
    op.drop_index(op.f('ix_scope_clarifications_scope_id'), table_name='scope_clarifications')
    op.drop_index(op.f('ix_scope_clarifications_scope_element_id'), table_name='scope_clarifications')
    op.drop_index(op.f('ix_scope_clarifications_organization_id'), table_name='scope_clarifications')
    op.drop_index(op.f('ix_scope_clarifications_assigned_to_user_id'), table_name='scope_clarifications')
    op.drop_table('scope_clarifications')
    op.drop_index(op.f('ix_scope_elements_source_onboarding_session_id'), table_name='scope_elements')
    op.drop_index(op.f('ix_scope_elements_scope_id'), table_name='scope_elements')
    op.drop_table('scope_elements')
    op.drop_index(op.f('ix_organization_teams_organization_id'), table_name='organization_teams')
    op.drop_index(op.f('ix_organization_teams_onboarding_session_id'), table_name='organization_teams')
    op.drop_table('organization_teams')
    op.drop_index(op.f('ix_organization_systems_organization_id'), table_name='organization_systems')
    op.drop_index(op.f('ix_organization_systems_onboarding_session_id'), table_name='organization_systems')
    op.drop_table('organization_systems')
    op.drop_index(op.f('ix_organization_suppliers_organization_id'), table_name='organization_suppliers')
    op.drop_index(op.f('ix_organization_suppliers_onboarding_session_id'), table_name='organization_suppliers')
    op.drop_table('organization_suppliers')
    op.drop_index(op.f('ix_organization_sites_organization_id'), table_name='organization_sites')
    op.drop_index(op.f('ix_organization_sites_onboarding_session_id'), table_name='organization_sites')
    op.drop_table('organization_sites')
    op.drop_index(op.f('ix_organization_profiles_organization_id'), table_name='organization_profiles')
    op.drop_index(op.f('ix_organization_profiles_onboarding_session_id'), table_name='organization_profiles')
    op.drop_table('organization_profiles')
    op.drop_index(op.f('ix_organization_processes_organization_id'), table_name='organization_processes')
    op.drop_index(op.f('ix_organization_processes_onboarding_session_id'), table_name='organization_processes')
    op.drop_table('organization_processes')
    op.drop_index(op.f('ix_organization_external_requirements_organization_id'), table_name='organization_external_requirements')
    op.drop_index(op.f('ix_organization_external_requirements_onboarding_session_id'), table_name='organization_external_requirements')
    op.drop_table('organization_external_requirements')
    op.drop_index(op.f('ix_organization_data_categories_organization_id'), table_name='organization_data_categories')
    op.drop_index(op.f('ix_organization_data_categories_onboarding_session_id'), table_name='organization_data_categories')
    op.drop_table('organization_data_categories')
    op.drop_index(op.f('ix_organization_activities_organization_id'), table_name='organization_activities')
    op.drop_index(op.f('ix_organization_activities_onboarding_session_id'), table_name='organization_activities')
    op.drop_table('organization_activities')
    op.drop_index('uq_isms_scopes_active_org', table_name='isms_scopes', postgresql_where=sa.text("status IN ('draft', 'pending_review')"))
    op.drop_index(op.f('ix_isms_scopes_validated_by_user_id'), table_name='isms_scopes')
    op.drop_index(op.f('ix_isms_scopes_owner_user_id'), table_name='isms_scopes')
    op.drop_index(op.f('ix_isms_scopes_organization_id'), table_name='isms_scopes')
    op.drop_index(op.f('ix_isms_scopes_based_on_onboarding_session_id'), table_name='isms_scopes')
    op.drop_table('isms_scopes')
    op.drop_index('uq_onboarding_sessions_active_org', table_name='onboarding_sessions', postgresql_where=sa.text("status IN ('draft', 'pending_review')"))
    op.drop_index(op.f('ix_onboarding_sessions_validated_by_user_id'), table_name='onboarding_sessions')
    op.drop_index(op.f('ix_onboarding_sessions_started_by_user_id'), table_name='onboarding_sessions')
    op.drop_index(op.f('ix_onboarding_sessions_organization_id'), table_name='onboarding_sessions')
    op.drop_table('onboarding_sessions')
    # ### end Alembic commands ###
