"""add email verification flow

Revision ID: a85651f7acaf
Revises: 8ae5b649a51f
Create Date: 2026-07-24 18:20:54.312155
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a85651f7acaf'
down_revision: str | None = '8ae5b649a51f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('membership_id', sa.Uuid(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_membership_id'), 'email_verification_tokens', ['membership_id'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_organization_id'), 'email_verification_tokens', ['organization_id'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.add_column('organization_members', sa.Column('status', sa.String(length=40), server_default='active', nullable=False))
    op.add_column('organizations', sa.Column('status', sa.String(length=40), server_default='active', nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(
        'ck_organization_members_status',
        'organization_members',
        "status IN ('pending', 'active', 'disabled')",
    )
    op.create_check_constraint(
        'ck_organizations_status',
        'organizations',
        "status IN ('pending_activation', 'active', 'archived')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_organizations_status', 'organizations', type_='check')
    op.drop_constraint('ck_organization_members_status', 'organization_members', type_='check')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('organizations', 'status')
    op.drop_column('organization_members', 'status')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_organization_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_membership_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
