type BaseTemplateInput = { title: string; greeting: string; body: string; cta?: { label: string; url: string }; code?: string; note?: string };

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);

export function renderBaseEmail(input: BaseTemplateInput, appUrl: string) {
  const logoUrl = `${appUrl.replace(/\/$/, "")}/images/normcore-logo.png`;
  const paragraphs = input.body.split("\n\n").map((paragraph) => `<p style="margin:0 0 18px;color:#294e5a;font-family:Arial,sans-serif;font-size:16px;line-height:1.65;">${escapeHtml(paragraph).replace(/\n/g, "<br>")}</p>`).join("");
  const cta = input.cta ? `<p style="margin:28px 0;text-align:center;"><a href="${escapeHtml(input.cta.url)}" style="display:inline-block;background:#11cbb3;border-radius:8px;color:#062c3a;font-family:Arial,sans-serif;font-size:15px;font-weight:700;padding:14px 24px;text-decoration:none;">${escapeHtml(input.cta.label)}</a></p>` : "";
  const code = input.code ? `<div style="background:#eefaf8;border:1px solid #9bded4;border-radius:10px;margin:26px 0;padding:20px;text-align:center;"><div style="color:#087970;font-family:Arial,sans-serif;font-size:11px;font-weight:700;letter-spacing:1.4px;text-transform:uppercase;">Activation token</div><div style="color:#062c3a;font-family:Consolas,Monaco,monospace;font-size:26px;font-weight:700;letter-spacing:4px;margin-top:10px;">${escapeHtml(input.code)}</div></div>` : "";
  const note = input.note ? `<p style="background:#fff8e9;border-left:3px solid #e5aa4d;color:#725323;font-family:Arial,sans-serif;font-size:13px;line-height:1.55;margin:22px 0;padding:12px 15px;">${escapeHtml(input.note)}</p>` : "";
  return `<!doctype html><html><body style="background:#edf7f6;margin:0;padding:24px 10px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width:620px;background:#ffffff;border:1px solid #cfe2e1;border-radius:14px;overflow:hidden;"><tr><td style="background:#062331;padding:24px 30px;"><img src="${escapeHtml(logoUrl)}" width="145" alt="NormCore" style="display:block;height:auto;max-width:145px;"></td></tr><tr><td style="padding:36px 40px 30px;"><h1 style="color:#062c3a;font-family:Arial,sans-serif;font-size:30px;line-height:1.2;margin:0 0 20px;">${escapeHtml(input.title)}</h1><p style="color:#294e5a;font-family:Arial,sans-serif;font-size:16px;line-height:1.65;margin:0 0 22px;">${escapeHtml(input.greeting)}</p>${paragraphs}${code}${cta}${note}</td></tr><tr><td style="border-top:1px solid #e1eeee;padding:22px 40px 26px;"><p style="color:#0b5962;font-family:Arial,sans-serif;font-size:14px;font-weight:700;margin:0 0 5px;">NormCore</p><p style="color:#718b90;font-family:Arial,sans-serif;font-size:12px;line-height:1.5;margin:0;">Security readiness, structured for ISO 27001.<br>This email was sent automatically by NormCore.</p></td></tr></table></td></tr></table></body></html>`;
}

export { escapeHtml };
