export type SecureDisposalReuseQuestionId = "p7_14_001" | "p7_14_002" | "p7_14_003";
export const A7_14_SECURE_DISPOSAL_REUSE_PLAN = "A7_14_SECURE_DISPOSAL_REUSE_PLAN";
export const A7_14_SECURE_DISPOSAL_REUSE_GAP_CODES = {
  A7_14_DISPOSAL_REUSE_RULES_PARTIAL: "A7_14_DISPOSAL_REUSE_RULES_PARTIAL", A7_14_DISPOSAL_REUSE_RULES_ABSENT: "A7_14_DISPOSAL_REUSE_RULES_ABSENT",
  A7_14_SANITIZATION_VERIFICATION_PARTIAL: "A7_14_SANITIZATION_VERIFICATION_PARTIAL", A7_14_SANITIZATION_VERIFICATION_ABSENT: "A7_14_SANITIZATION_VERIFICATION_ABSENT",
  A7_14_DISPOSAL_REUSE_TRACEABILITY_PARTIAL: "A7_14_DISPOSAL_REUSE_TRACEABILITY_PARTIAL", A7_14_DISPOSAL_REUSE_TRACEABILITY_ABSENT: "A7_14_DISPOSAL_REUSE_TRACEABILITY_ABSENT",
} as const;
export type SecureDisposalReuseQuestion = { id: SecureDisposalReuseQuestionId; type: "policy_process" | "application" | "proof_traceability"; status: "main"; title: { fr: string; en: string }; question: { fr: string; en: string }; helpText: { fr: string; en: string }; suggestedEvidence: { fr: string; en: string } };
export const secureDisposalReuseQuestions: SecureDisposalReuseQuestion[] = [
  { id: "p7_14_001", type: "policy_process", status: "main", title: { fr: "Règles d’élimination ou réutilisation", en: "Disposal or reuse rules" }, question: { fr: "Votre organisation a-t-elle défini un processus permettant d’identifier les équipements contenant des supports de stockage et de déterminer, avant leur élimination, retour, transfert ou réutilisation, comment les données sensibles et logiciels sous licence doivent être traités selon le risque ?", en: "Has your organization defined a process for identifying equipment containing storage media and determining, before disposal, return, transfer, or reuse, how sensitive data and licensed software should be handled according to risk?" }, helpText: { fr: "Le processus couvre les équipements réellement présents contenant du stockage et leurs chemins de sortie ou réutilisation. Le matériel loué retourné avec du stockage ne rend pas automatiquement le contrôle non applicable.", en: "The process covers equipment actually present that contains storage and its exit or reuse paths. Leased equipment returned with storage does not automatically make the control not applicable." }, suggestedEvidence: { fr: "- processus de sortie ou réaffectation ;\n- inventaire des équipements ;\n- responsabilités ;\n- règles de traitement des données et logiciels.", en: "- disposal or reassignment process;\n- equipment inventory;\n- responsibilities;\n- data and software handling rules." } },
  { id: "p7_14_002", type: "application", status: "main", title: { fr: "Vérification de la sanitization", en: "Sanitization verification" }, question: { fr: "Avant qu’un équipement contenant du stockage soit éliminé, retourné, transféré ou réutilisé, l’organisation vérifie-t-elle effectivement que les données sensibles et logiciels sous licence ont été supprimés, rendus non récupérables ou autrement traités de manière appropriée au support et au risque ?", en: "Before equipment containing storage is disposed of, returned, transferred, or reused, does the organization effectively verify that sensitive data and licensed software have been removed, rendered unrecoverable, or otherwise handled appropriately for the media and risk?" }, helpText: { fr: "Choisir une méthode adaptée au support, à la sensibilité, au risque et à la possibilité de réutilisation. Aucune méthode, aucun outil, aucun nombre de passes ni destruction physique n’est universellement obligatoire.", en: "Choose a method appropriate to the media, sensitivity, risk, and possibility of reuse. No method, tool, number of passes, or physical destruction is universally mandatory." }, suggestedEvidence: { fr: "- vérification avant sortie ;\n- dossiers de réaffectation ;\n- preuves de traitement ;\n- contrôles de retour ou transfert.", en: "- pre-release verification;\n- reassignment records;\n- handling evidence;\n- return or transfer controls." } },
  { id: "p7_14_003", type: "proof_traceability", status: "main", title: { fr: "Traçabilité de l’élimination ou réutilisation", en: "Disposal or reuse traceability" }, question: { fr: "Votre organisation peut-elle démontrer, pour les équipements concernés, la décision de mise au rebut ou de réutilisation, la méthode appliquée, sa vérification, les éventuels traitements réalisés par un tiers et la clôture correspondante ?", en: "Can your organization demonstrate, for relevant equipment, the disposal or reuse decision, the method applied, its verification, any third-party processing, and the corresponding closure?" }, helpText: { fr: "Conserver une piste de preuve proportionnée reliant l’actif, la décision, la méthode, le résultat de vérification, les tiers éventuels et la clôture.", en: "Retain proportionate evidence linking the asset, decision, method, verification result, any third party, and closure." }, suggestedEvidence: { fr: "- décision de mise au rebut ou réutilisation ;\n- preuve de méthode et vérification ;\n- dossiers tiers ;\n- clôture et exceptions.", en: "- disposal or reuse decision;\n- method and verification evidence;\n- third-party records;\n- closure and exceptions." } },
];
